### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by forthwist** [WesCook/Homestead#1]
Hi there!  
I've got Homestead hosted over at Nodecraft with a plan that allocates 4gb of ram which with 4 people running around doing stuff we're only using about 60% of it (most packs we've played eat up about 90%).

However our log is full of:
`[23:49:12] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4251ms behind, skipping 85 tick(s)`

`[23:49:30] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4602ms behind, skipping 92 tick(s)`

And cpu usage is reported at 93.4% usage.  I don't have access to the full server stats unfortunately, and the console isn't providing much hint at what might be causing this.

Any insight appreciated, I've hit the end of my very limited knowledge on the topic! --Let me know if there's any more info I can provide.

**Comment by WesCook** [comment]
Hey there,

I don't know how fast Nodecraft's CPUs are, but it sounds like they're doing okay.  For memory, 4GB should be enough memory to run this pack.  The only area I would expect you to run into trouble is with terrain generation.  This is the unfortunate reality of most heavily-modded packs.

What I usually do is generate a 100 chunk radius around spawn on first load, then reboot the game server.  This helps eliminate the problem of everybody moving in different directions on first spawn.

Still, even a single person generating chunks has a good chance of tanking your TPS, which is what results in those warnings.  It also will also slowly increase memory usage, as worldgen is usually leaky.

Other than upgrading hardware, you don't have many options other than asking players not to explore new chunks when others are online.  Alternatively, you can consider a world border and generate chunks up to that point.  However, Homestead does require some exploration and in general I find this hurts the immersion.

Sorry I don't have a simple fix for you, but TPS is a problem universal to most modded Minecraft servers.  While I've resolved the low-hanging problems such as chunk runaway problems, some mods are just heavier in their generation (such as WTF's Expedition).

So my guess is that it's related to world-gen in your case.  You can test this by rebooting the game server and measuring TPS (`/forge tps`) without exploring at all.

If you think there may be another issue at play, please let me know and I'll see if there's anything I can do.

Cheers.

**Comment by dpmcg89** [comment]
Hey WesCook,

Loving the pack.  It's so good.

> What I usually do is generate a 100 chunk radius around spawn on first load, then reboot the game server. This helps eliminate the problem of everybody moving in different directions on first spawn.

I think this would solve most of my problems too.  How exactly do you gen these chunks?  Is there a server command I can use?

Thanks

**Comment by WesCook** [comment]
I used a mod called [chunkpregenerator](https://minecraft.curseforge.com/projects/chunkpregenerator) on my last server.  Another option is [chunkgen](https://minecraft.curseforge.com/projects/chunkgen), though I've heard it doesn't play well with Railcraft.

Or if all else fails, there's a [vanilla option](https://www.youtube.com/watch?v=7WSMgOVsnCU) as well.

**Comment by dpmcg89** [comment]
Holy quick response, batman.

Thanks so much!  I'll give that a shot.
