### ISSUE TITLE
Game Crashed on startup

### ISSUE THREAD

**Issue by RealBagel** [WesCook/Homestead#10]
Crashed on 7/7 on FML. 
http://paste.atlauncher.com/view/ab2d9b13
Any idea what causes this?

**Comment by WesCook** [comment]
It appears you're only allocating 1.5GB of memory in the launcher.  Is this correct?

Unfortunately Homestead and most other 1.10+ packs will require much more memory.  I'd suggest 4GB minimum.  You could *maybe* get away with 3GB, but be sure to leave some for your operating system as well.

If your system isn't capable of allocating this much memory, then I'm afraid you won't be able to play the pack.
