### ISSUE TITLE
Launching server ends with [Server Shutdown Thread/INFO]

### ISSUE THREAD

**Issue by frimdo** [WesCook/Homestead#101]
I installed last server (1.10.1) using ATLauncher and launched it with LaunchServer.bat It ends with error every time. Complete log is [here](https://gist.github.com/frimdo/c8d7aa6cb6e44efdd31cdbb524a7732e).

I have no idea what is happening, but I keep getting the same error with all versions. Any ideas? Thanks!

**Comment by frimdo** [comment]
Oh! You need to accept EULA (line 835). OK, my bad. Awesome modpack btw :)

**Comment by WesCook** [comment]
No worries.  The eula thing gets me every time, too.

Cheers.
