### ISSUE TITLE
How do cave-in mechanics work?

### ISSUE THREAD

**Issue by jforr** [WesCook/Homestead#104]
Is the cave-in mechanic added by another mod or was that one of yours?  I'm having a hard time figuring out the rules of how to keep things from falling in and am just looking for some clarity on that.

Thanks for the awesome modpack, this is by far my favorite from all the years I've played the game.

**Comment by WesCook** [comment]
Hi jforr,

Thanks for your message.  The cave-in mechanic is added by WTF's Expedition.  Or more specifically a forked version called [Expedition Homestead-Edition](https://github.com/WesCook/Expedition-Homestead-Edition).

If I'm not mistaken, cave-ins can be disabled within the configs.  In truth they never worked as well as I had hoped, and I probably should have disabled them myself.

I hope you enjoy the pack!
