### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by RestrictedDruid** [WesCook/Homestead#106]
Hi there,
I've found your pack a couple of days ago and it looks so awesome!  The perfect medium of Terrafirmcraft, but done with mods that I enjoy.  I'm really looking forward to diving in, but I'm running into some trouble. 
 
I'm playing on a Macbook Pro with 8GB of RAM and I've allocated 4,608 to ATLauncher.  I'm able to boot the pack and I've disabled intensive pieces like BetterFoliage's leaves, but it's running very slow.  Adding in Optifine would likely help boost FPS, but when I add it into the "mods" folder, I crash.  

Here is a copy of the crash log that occurs when I add Optifine 1.10.2 HD_U_E7:  https://controlc.com/a299aca7

I've also tried downloading and using OptiFine 1.10.2 HD_U_H5, which is an updated version of the file the pack recommends during install and I still crash.

If the answer is there's no way to make it run faster for me and I just need a beefier computer, that's ok.  But it seems like I'm so close to running the pack well and potentially missing something.  Thanks in advance!

**Comment by WesCook** [comment]
To address the performance issues, as you said I'd guess it's just a question of computing power.

Memory issues aren't usually the cause of low framerate.  However, with 8GB system memory you should be able to safely allocate 6GB to the game.

Homestead marks the visual mods as optional, so you can try disabling those if they're not important to you.  You can also use Optifine to tweak the game's visual settings.  Lowering render distance, turning off particles, and lower various detail settings may help some.

As for the crash with newer versions of Optifine, that appears related to this bug:
https://github.com/sp614x/optifine/issues/4824

I'm afraid I can't help there.  There is a suggestion to use Amazon's Corretto JDK, which you could try instead.

As this isn't a bug in Homestead of something actionable for me to do, I'll go ahead and mark this as closed.  Hopefully this has helped some though.  Good luck, and if you're able to get it running well, do enjoy the pack.
