### ISSUE TITLE
[Possible Bug] Pam's Harvestcraft/IE Hemp crops immune to winter effects.

### ISSUE THREAD

**Issue by EchoingZen** [WesCook/Homestead#12]
Pam's Harvestcraft crops do not wither during winter months. My wheat died but my Pam's Harvestcraft and IE Hemp fields were just fine.

**Comment by WesCook** [comment]
Hi Zen,

Thanks again for another bug report.  This one is unfortunately a known issue, but there's nothing I can do about it right now.  Tough as Nails has a very limited API, and even in the latest versions these mods are not completely compatible.

It's something which may come in a later version if TaN can add support.  But for now, the only thing I can do is hope it becomes a priority.  Sorry!

Thanks again for the report, though I'm going to close this as there's no actions I can take to improve the situation right now.
