### ISSUE TITLE
Sorting chests delete everything, very buggy

### ISSUE THREAD

**Issue by makeshiftwings** [WesCook/Homestead#14]
This is in multiplayer. I finally got around to putting all my stuff into sorting chests. The filter interface is very buggy, most choices don't work, and after selecting a bad choice, all filter buttons stop working. Still, the chests seemed to work fine stuck on the default of keeping items already in their inventories. But then I logged off and logged back in, and all the chests were completely empty; all items had been deleted. Quite an unpleasant bug.

**Comment by WesCook** [comment]
That is a nasty bug.  I'm sorry about that, I didn't notice this before.

I'm going to need to do some more testing to see if I can get these chests into a usable state.  I hope not many people have lost items as a result of this.

I know it's rarely ideal, but the pack should have created automatic backups if you'd like to revert.  Or at the very least, you can figure out what items existed previously so you can spawn them back in.

Thank you for the report.

**Comment by makeshiftwings** [comment]
Yeah, we do have backups so it wasn't the end of the world. Thanks for looking into it. I love the pack by the way! :)

**Comment by WesCook** [comment]
I've decided to simply remove Refined Relocation in the latest version.  It was my mistake for ever including it in the first place - it's too unstable.

I've just released v1.4 which removes this mod.  As such I'm going to mark this as closed.
