### ISSUE TITLE
Item duplications

### ISSUE THREAD

**Issue by makeshiftwings** [WesCook/Homestead#15]
There seem to be a few actions that duplicate items in multiplayer:

- Punching a painting down off a wall will give you two paintings.
- Punching an item frame off the wall gives you two item frames, unless it was a Quark dyed item frame, in which case you don't get the dyed frame, you only get a regular frame.
- You can grind a leather strap to get a leather square, which you can cut into two leather straps

**Comment by WesCook** [comment]
I've fixed all three issues in v1.4.  Thanks for the great report!
