### ISSUE TITLE
Incompatability between SoundPhysics and Animania

### ISSUE THREAD

**Issue by tobi1449** [WesCook/Homestead#16]
Results in the following exception quickly after loading the world:

> [24/7/2017 23:13:38 PM] java.lang.NullPointerException: Ticking entity
> [24/7/2017 23:13:38 PM] 	at com.sonicether.soundphysics.SoundPhysics.calculateEntitySoundOffset(SoundPhysics.java:219)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.entity.Entity.func_184185_a(Entity.java:972)
> [24/7/2017 23:13:38 PM] 	at com.animania.entities.amphibians.EntityAmphibian.func_70637_d(EntityAmphibian.java:120)
> [24/7/2017 23:13:38 PM] 	at com.animania.entities.amphibians.EntityAmphibian.startJumping(EntityAmphibian.java:126)
> [24/7/2017 23:13:38 PM] 	at com.animania.entities.amphibians.EntityAmphibian.func_70619_bc(EntityAmphibian.java:157)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:906)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:685)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:41)
> [24/7/2017 23:13:38 PM] 	at com.animania.entities.amphibians.EntityAmphibian.func_70636_d(EntityAmphibian.java:213)
> [24/7/2017 23:13:38 PM] 	at com.animania.entities.amphibians.EntityDartFrogs.func_70636_d(EntityDartFrogs.java:253)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.world.World.func_72866_a(World.java:1964)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.world.World.func_72870_g(World.java:1934)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.world.World.func_72939_s(World.java:1750)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
> [24/7/2017 23:13:38 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> [24/7/2017 23:13:38 PM] 	at java.lang.Thread.run(Thread.java:748)

This has been fixed in Animania v1.2.1, so an update would be great.

**Comment by WesCook** [comment]
Are you playing the latest version of Homestead?  This was supposed to be fixed in v1.3...  I'll look into it soon.

Previous bug report at #4.

**Comment by tobi1449** [comment]
According to ATLauncher I'm on 1.3 and I don't see any newer version. And the ATLauncher page for Homestead also shows Animania at version 1.2

**Comment by WesCook** [comment]
Okay, thank you.  I'm not sure how that happened but I'll definitely include it in v1.4.

**Comment by WesCook** [comment]
I've patched this officially in v1.4.  Hopefully the bug stays dead this time...

Much thanks for the report!
