### ISSUE TITLE
Saltpeter recipes not listed in JEI

### ISSUE THREAD

**Issue by nedellis** [WesCook/Homestead#17]
Right click on Saltpeter doesn't show recipes.

**Comment by WesCook** [comment]
I'm not able to replicate this issue.  Are you selecting the item `Saltpetre` from WTF's Expedition?  The saltpeter from Railcraft has been disabled.

Alternatively, you can view recipes for `Niter`.  They are ore dictionaried together.

**Comment by nedellis** [comment]
Saltpeter from WTF. Right click on it and it doesn't show recipes. I'm on 1.4.0. 
Also any "ore" item in WTF seems to not have a recipe, according to JEI. For example i think "Red granite gold ore" should work in the the Immersive Enginering Crusher, but the recipe it's not there.

**Comment by WesCook** [comment]
If you mine a biome-specific ore block (eg. Red Granite Gold), it will drop regular gold blocks.  Those should show correctly in JEI.

Regarding saltpeter, I'm not sure why that would be as I can't replicate it.  However does Niter show the recipes?

Alternatively, you can start at gunpowder and show recipes to create it.  That's the primary use of saltpeter.

**Comment by nedellis** [comment]
It's strange that you can't replicate it. Sorry to ear.
Niter shows the recipes with rightclick and i can see Saltpeter in the gunpowder and fire charge recipe too.  
I hope no other items has this bug, because it could be very annoying :D.
Btw, best pack ever.

**Comment by WesCook** [comment]
It seems like an odd issue, but as I can't replicate and because it's relatively minor, I'm going to close this bug for now.  Feel free to open it again if you find other items with this problem.

Thanks for the kind words, I'm glad you like the pack.  Enjoy!
