### ISSUE TITLE
Strange lag and oak leaves bug in 1.4.1

### ISSUE THREAD

**Issue by nedellis** [WesCook/Homestead#19]
Dunno why but i can't puch oak leaves in 1.4.1. I can destroy all other leaves but oak. For oak i have to use axe.
Also i have strange lag like when you play online. Sometimes i destroy a block but it doesn't destroy until few seconds.

**Comment by WesCook** [comment]
Thanks for the report.  Sounds like the same bug as #18, but I missed another entry.

Looks like there'll be a 1.4.2.

**Comment by WesCook** [comment]
I've release 1.4.2 to address this.  Hopefully that's the last minor issue.

I opted to revert the HarvestTweaks changes from 1.4 as I'd rather have a little bit of logspam than play whack-a-mole with these issues.

Thanks again for the report.
