### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by griffin409** [WesCook/Homestead#2]
every time i try to launch the modpack it goes through all the startup loading, but once it gets to the 3/7,  5/5 it always stops working.

Does it have anything to do with java 8 or is it a internal error with me?

**Comment by WesCook** [comment]
Typically these errors are caused by running out of memory.  You'll need to check your crashlogs to verify though.  They can be found in the game directory under the /crash-reports directory.

If that's indeed the cause, you can try increasing memory allocation in the ATLauncher's settings menu.

**Comment by griffin409** [comment]
i believe that the memory isn't an issue since i have the memory allocation set to 4096, so the memory isn't usually an issue, this is more the issues im getting

17:49:37] [Client thread/ERROR] [FML]: Exception loading model for variant stevescarts:upgrade#facing=west,type=20
[01/7/2017 17:49:37 PM] net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model stevescarts:upgrade#facing=west,type=20 with loader VariantLoader.INSTANCE, skipping

seems that the mods are having issues, weather that be a conflict with my pc or something im not sure, sometimes the mods that are giving me issues are different.

**Comment by WesCook** [comment]
A number of mods have model errors, but it shouldn't prevent the game from launching.

Can you upload a crash log?  Or if a crash log doesn't exist, can you upload a regular log instead?

**Comment by griffin409** [comment]
how would i get the log on the atlauncher, just hit the upload log on it?

**Comment by WesCook** [comment]
ATLauncher includes a full log in the console window.  You can upload it manually to a site like Pastebin or Github Gists, or use the Upload Log feature of ATLauncher.

**Comment by griffin409** [comment]
http://paste.atlauncher.com/view/17c2586d

**Comment by WesCook** [comment]
I'm afraid I don't see anything that would indicate what's wrong.  To be 100% sure, there's no crash log in the /crash-reports directory, right?

4GB of memory should be enough for the pack.  Though based on the log output, it's only getting about 1/3rd of the way there.

Just to clarify, is the pack crashing outright during load, or does it freeze up and stop progressing?  If so, does the Forge hammer icon stop moving as well?

**Comment by griffin409** [comment]
it fully stops responding, every time, the hammer also stops

**Comment by WesCook** [comment]
That sure sounds like a memory issue.  It looks like you've set the max to 3.5GB.  I'd suggest you try allocating from 4-6GB max, and see if that has any effect.  Be sure to leave a couple gigs for your operating system to work with though.

Also, I need to repeat my request to verify that there's no crash log.  If it's present, that would make the problem much more clear.

**Comment by griffin409** [comment]
alright i shall look

**Comment by griffin409** [comment]
i apologize, i can not find the any crash reports.

**Comment by WesCook** [comment]
That's fine, it may not exist if the game didn't properly exit.  I'd still suggest trying to increase the memory though and see if that has any effect.

If that's not it, then I'm not sure what else the cause could be.  You might try deleting the instance and reinstalling it from scratch, in case something went wrong (be sure to backup anything important if you've had it working in the past).

**Comment by griffin409** [comment]
understood, i've increased the memory to 4 GB and im launching it now, if it doesnt work then ill reinstall it, thanks for the help.

**Comment by WesCook** [comment]
Any success with that change?

**Comment by griffin409** [comment]
No sadly

**Comment by WesCook** [comment]
Did it progress any further, or break at about the same spot?  If it made it further, that may indicate we're on the right path.  Otherwise, I'm all out of suggestions unfortunately.

**Comment by griffin409** [comment]
Same spot but now my atlauncher is giving me issues all together

**Comment by griffin409** [comment]
So ill just redownload it after in done restarting my PC to factory settings tomorrow, have a good night
