### ISSUE TITLE
Infinite buckets. (What is real?)

### ISSUE THREAD

**Issue by krzys189** [WesCook/Homestead#23]
When makig the bucket of slop you can use a standard milk bucket in the recipe (not fresh milk). When you finish the recipe you get a bucket back. And when you dump the bucket in the trough or feed them directly to the piggies you also get a bucket back. I don`t know what you can do with it, but it really bothers me. You spend a whole day in the mine to get some iron. while you can just sit at home and abuse this.

**Comment by krzys189** [comment]
Also, how can you get creosote oil?

**Comment by WesCook** [comment]
I'll look into the buckets dupe, thanks.

Creosote oil can be made using a Coke Oven from Immersive Engineering.  Put in Charcoal or Wood to convert them, and slowly accumulate creosote.  This can be stored in buckets or glass bottles.

**Comment by krzys189** [comment]
Thanks!

**Comment by WesCook** [comment]
I've just pushed v1.4.4 with a fix.  Thanks for the report!
