### ISSUE TITLE
Crashing on Startup, can't even get to the Main Menu

### ISSUE THREAD

**Issue by iMinecraftianz** [WesCook/Homestead#24]
Hello,
I downloaded the Pack, and I have tried re-installing multiple times and every time I launch the game it finishes loading the mods and then crashes before I get to the Menu to create a world etc. I dont understand as my friend who has done the same thing I have and it works for them first time. Here is the Crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  LoadingPluginHardModeTweaks (HardModeTweaks-1.10-1.2.2.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.19-universal.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  literalascension (literalascension-1.10.2-1.0.2.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  AstralCore (astralsorcery-1.4.5.jar)
  AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  SPFMLLoadingPlugin (soundphysics-mc1.10.2-v1.0.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.9.jar)
  DummyPlugin (ForgeEndertech-1.10.2-1.3.4.0-build.0057.jar)
  Extra Alchemy ASM (extraalchemy-0.3.4-release.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.6.1.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.7.jar)
  IvToolkit (IvToolkit-1.3.3-1.10.jar)
  llibrary (llibrary-1.7.6-1.10.2.jar)
  BlurPlugin (Blur-1.0.3-13.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 8/4/17 11:51 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:254)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:245)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:205)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:61)
	at hellfirepvp.astralsorcery.client.util.resource.BindableResource.allocateGlId(BindableResource.java:66)
	at hellfirepvp.astralsorcery.client.util.TexturePreloader.preloadMandatoryTextures(TexturePreloader.java:45)
	at hellfirepvp.astralsorcery.client.util.TexturePreloader.doPreloadRoutine(TexturePreloader.java:28)
	at hellfirepvp.astralsorcery.client.util.resource.AssetLibrary.func_110549_a(AssetLibrary.java:66)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureUtil.func_110993_a(TextureUtil.java:254)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110995_a(TextureUtil.java:245)
	at net.minecraft.client.renderer.texture.TextureUtil.func_110989_a(TextureUtil.java:205)
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:61)
	at hellfirepvp.astralsorcery.client.util.resource.BindableResource.allocateGlId(BindableResource.java:66)
	at hellfirepvp.astralsorcery.client.util.TexturePreloader.preloadMandatoryTextures(TexturePreloader.java:45)
	at hellfirepvp.astralsorcery.client.util.TexturePreloader.doPreloadRoutine(TexturePreloader.java:28)
	at hellfirepvp.astralsorcery.client.util.resource.AssetLibrary.func_110549_a(AssetLibrary.java:66)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:763)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 21715416 bytes (20 MB) / 1038876672 bytes (990 MB) up to 1038876672 bytes (990 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -Xms256M -Xmx1024M -XX:MetaspaceSize=128M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 Optifine OptiFine_1.10.2_HD_U_E3 147 mods loaded, 147 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316-universal.jar) 
	UCHIJA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316-universal.jar) 
	UCHIJA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJA	hardmodetweakscore{1.0.0} [Hard Mode Tweaks Core] (minecraft.jar) 
	UCHIJA	ivtoolkit{1.3.3-1.10} [IvToolkit] (minecraft.jar) 
	UCHIJA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJA	hardlib{1} [HardLib] (1.10.2-HardLib-v1b.jar) 
	UCHIJA	expindustry{1.1.0b} [Expanded Industry] (1.10.2-ExpandedIndustry-1.1.0b.jar) 
	UCHIJA	forgeendertech{1.10.2-1.3.4.0} [Forge Endertech] (ForgeEndertech-1.10.2-1.3.4.0-build.0057.jar) 
	UCHIJA	adchimneys{1.10.2-1.2.8.0} [Advanced Chimneys] (AdChimneys-1.10.2-1.2.8.0-build.0061.jar) 
	UCHIJA	animania{1.2.2} [Animania] (animania-1.10.2-1.2.2.jar) 
	UCHIJA	antiqueatlas{4.4.5} [Antique Atlas] (antiqueatlas-1.9.4-4.4.5.jar) 
	UCHIJA	antiqueatlasoverlay{1.2} [Antique Atlas Overlay] (antiqueatlas-1.9.4-4.4.5.jar) 
	UCHIJA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJA	AppleCore{2.2.2} [AppleCore] (AppleCore-mc1.10.2-2.2.2.jar) 
	UCHIJA	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.10.2-1.0.7.jar) 
	UCHIJA	architecturecraft{1.7.3} [ArchitectureCraft] (ArchitectureCraft-1.7.3-mc1.10.2.jar) 
	UCHIJA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJA	astralsorcery{1.4.5} [Astral Sorcery] (astralsorcery-1.4.5.jar) 
	UCHIJA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHIJA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.6.jar) 
	UCHIJA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJA	theoneprobe{1.4.14} [The One Probe] (theoneprobe-1.1x-1.4.14.jar) 
	UCHIJA	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJA	shetiphiancore{3.3.9} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.9.jar) 
	UCHIJA	terraqueous{1.2.25} [Terraqueous] (terraqueous-1.10.0-1.2.25.jar) 
	UCHIJA	betterwithmods{0.14.23 Beta} [Better With Mods] (Better With Mods-0.14.3-1.10.2.jar) 
	UCHIJA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	UCHIJA	betterfoliage{2.1.7} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.7.jar) 
	UCHIJA	betterquesting{2.3.234} [Better Questing] (BetterQuesting-2.3.234.jar) 
	UCHIJA	bqt{0.9} [Better Questing Triggerer] (BetterQuestingTriggerer-0.9.jar) 
	UCHIJA	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UCHIJA	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	UCHIJA	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	UCHIJA	bigdoors{1.10.2-1.3.0} [Big Doors] (BigDoors-1.10.2-1.3.0.jar) 
	UCHIJA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.10-1.5.1.jar) 
	UCHIJA	bloodmoon{1.5.1} [Bloodmoon] (Bloodmoon-MC1.10.2-1.5.1.jar) 
	UCHIJA	blur{1.0.3-13} [Blur] (Blur-1.0.3-13.jar) 
	UCHIJA	infinitylib{1.10.2-0.11.0} [InfinityLib] (infinitylib-0.11.0.jar) 
	UCHIJA	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.11.0.jar) 
	UCHIJA	ceramics{1.10.2-1.1.6b} [Ceramics] (Ceramics-1.10.2-1.1.6b.jar) 
	UCHIJA	charcoal_pit{1.4} [Charcoal Pit] (CharcoalPit-[1.10.2]-1.4.jar) 
	UCHIJA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJA	controlling{1.0.5} [Controlling] (Controlling-1.0.5.jar) 
	UCHIJA	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UCHIJA	coralreef{1.0} [Coral Reef] (CoralReef-1.2.jar) 
	UCHIJA	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJA	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	UCHIJA	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UCHIJA	defaultworldgenerator-port{1.9.4-0.4} [Default World Generator] (DefaultWorldGenerator-port-1.9.4-0.4.jar) 
	UCHIJA	double_jump{1.0.1} [DoubleJump] (DoubleJump-1.10.2-1.0.0.jar) 
	UCHIJA	dsurround{3.4.6.1} [§3Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.4.6.1.jar) 
	UCHIJA	presets{3.4.6.1} [§3Presets!] (DynamicSurroundings-1.10.2-3.4.6.1.jar) 
	UCHIJA	ediblebugs{1.4.6.2099} [Edible Bugs Mod] (ediblebugs-MC1.10.02_EB1.4.6.2099.jar) 
	UCHIJA	enchdesc{1.0.0.0} [Enchantment Descriptions] (EnchantmentDescriptions-1.10.2-1.0.0.0.jar) 
	UCHIJA	enhancedvisuals{1.0} [Enhanced Visuals] (EnhancedVisuals v1.1.0 mc1.10.2.jar) 
	UCHIJA	januslib{0.1-dev} [Janus Compatibility Library] (januslib-0.1.jar) 
	UCHIJA	extraalchemy{0.3.4-release} [Extra Alchemy] (extraalchemy-0.3.4-release.jar) 
	UCHIJA	fairylights{2.1.2} [Fairy Lights] (fairylights-2.1.2-1.10.2.jar) 
	UCHIJA	farmingforblockheads{1.1.15} [Farming for Blockheads] (FarmingForBlockheads_1.10.2-1.1.15.jar) 
	UCHIJA	flintmod{7.5} [Flint Instead of Wood] (FlintInsteadOfWood[1.10.2]-7.5.jar) 
	UCHIJA	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.2-anarchy.jar) 
	UCHIJA	grapplemod{1.10.2-v10} [Grappling hook mod] (grapplemod-1.10.2-v10.jar) 
	UCHIJA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.9.4-1.8.jar) 
	UCHIJA	hardmodetweaks{@1.10-1.2.2@} [Hard Mode Tweaks] (HardModeTweaks-1.10-1.2.2.jar) 
	UCHIJA	homesteadcompanion{1.6} [Homestead Companion] (HomesteadCompanion-1.10.2-1.6.jar) 
	UCHIJA	furniture{1.1.3} [How 'Bout That Furniture] (HowBoutThatFurniture-1.2.1.jar) 
	UCHIJA	immcraft{1.3.6} [Immersive Craft] (immcraft-1.1x-1.3.6.jar) 
	UCHIJA	immersivepetroleum{1.1.2} [Immersive Petroleum] (immersivepetroleum-1.10.2-1.1.2.jar) 
	UCHIJA	inventorysorter{0.11.0+47} [Simple Inventory sorting] (inventorysorter-1.10.2-0.11.047.jar) 
	UCHIJA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UCHIJA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.10.2-0.11.0.jar) 
	UCHIJA	itemzoom{1.4} [Item Zoom] (itemzoom1.10.2-1.4.jar) 
	UCHIJA	jaff{1.5.3_for_1.10.2} [Just a Few Fish] (JustAFewFish-1.5.3_for_1.10.2.jar) 
	UCHIJA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UCHIJA	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UCHIJA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.10.2.jar) 
	UCHIJA	literalascension{1.10.2-1.0.2.2} [Literal Ascension] (literalascension-1.10.2-1.0.2.2.jar) 
	UCHIJA	login_shield{1.10.2-19-gd16e7e0} [Login Shield] (Login_Shield-1.10.2-19-gd16e7e0.jar) 
	UCHIJA	loottweaker{0.0.6.3} [LootTweaker] (LootTweaker-1.10.2-0.0.6.3.jar) 
	UCHIJA	mobends{0.22.5} [Mo'Bends] (mobends-0.22.5_for_MC-1.10.2.jar) 
	UCHIJA	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UCHIJA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.3.jar) 
	UCHIJA	modtweaker{2.0.13} [Mod Tweaker] (ModTweaker2-2.0.13.jar) 
	UCHIJA	moredefaultoptions{1.10.2-0.0.2} [MoreDefaultOptions] (moredefaultoptions-1.10.2-0.0.2.jar) 
	UCHIJA	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.10.2.jar) 
	UCHIJA	mowziesmobs{1.3.2} [Mowzie's Mobs] (mowziesmobs-1.3.2.jar) 
	UCHIJA	mxtune{0.4.0-dev.23} [mxTune] (mxtune-1.10.2-0.4.0-dev.23.jar) 
	UCHIJA	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.10.2-1.3.1.jar) 
	UCHIJA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (NetherPortalFix_1.10.2-3.3.4.jar) 
	UCHIJA	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCHIJA	nutrition{1.5.0} [Nutrition] (Nutrition-1.10.2-1.5.0.jar) 
	UCHIJA	openglider{@VERSION@} [Open Glider] (OpenGlider-1.10.2-1.0.0.jar) 
	UCHIJA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pams HarvestCraft 1.10.2j.jar) 
	UCHIJA	pumpkincarving{1.0} [Pumpkin Carving] (PumpkinCarving1.10.2-1.0.jar) 
	UCHIJA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJA	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
	UCHIJA	RealisticTorches{1.6.4} [Realistic Torches] (RealisticTorches-1.10.2-1.6.4.jar) 
	UCHIJA	reauth{3.5.0} [ReAuth] (ReAuth-3.5.0.jar) 
	UCHIJA	reccomplex{1.4.4-1.10} [Recurrent Complex] (RecurrentComplex-1.4.4-1.10.jar) 
	UCHIJA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.9.4-1.7.4.jar) 
	UCHIJA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJA	rockhounding_surface{${version_mod}} [Rockhounding: Surface] (rockhounding_surface-1.10.2-1.15.jar) 
	UCHIJA	ropebridge{1.10.2-2.1.0} [Rope Bridge] (ropebridge-1.10.2-2.1.0.jar) 
	UCHIJA	roughMobs{1.0} [Rough Mobs] (roughMobs1.0.11-1.10.2.jar) 
	UCHIJA	RTG{4.1.2.4} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.4.jar) 
	UCHIJA	rustic{0.1.2.2} [Rustic] (rustic-0.1.2.2.jar) 
	UCHIJA	Signals{1.0} [Signals] (Signals-1.10.2-0.5.1-universal.jar) 
	UCHIJA	ToughAsNails{1.1.1.19} [Tough As Nails] (ToughAsNails-1.9.4-1.1.1.19-universal.jar) 
	UCHIJA	slurp{0.2} [Slurp] (slurp-1.10.2-0.2.jar) 
	UCHIJA	SophisticatedWolves{3.6.1} [SophisticatedWolves] (SophisticatedWolves-3.6.5.jar) 
	UCHIJA	soundphysics{1.0.0} [Sound Physics] (soundphysics-mc1.10.2-v1.0.0.jar) 
	UCHIJA	LunatriusCore{1.1.2.38} [LunatriusCore] (LunatriusCore-1.10.2-1.1.2.38-universal.jar) 
	UCHIJA	Stackie{1.6.0.44} [Stackie] (Stackie-1.10.2-1.6.0.44-universal.jar) 
	UCHIJA	stacksonstacks{1.1.4} [stacksonstacks] (StacksOnStacks2-1.1.4.jar) 
	UCHIJA	bq_standard{2.3.131} [Standard Expansion] (StandardExpansion-2.3.131.jar) 
	UCHIJA	stevescarts{2.2.0.86} [Steve's Carts 2] (StevesCarts-1.10.2-2.2.0.86.jar) 
	UCHIJA	streams{0.3} [Streams] (Streams-1.9.4-0.3.jar) 
	UCHIJA	timberjack{1.5} [Timberjack] (Timberjack_1.10.2-1.5.jar) 
	UCHIJA	totemic{1.10.2-0.8.3} [Totemic] (Totemic-1.10.2-0.8.3.jar) 
	UCHIJA	tumbleweed{1.10-0.4.2} [Tumbleweed] (tumbleweed-1.10-0.4.2.jar) 
	UCHIJA	undergroundbiomes{1.0.v.18} [Underground Biomes] (UndergroundBiomesConstructs-1.10-1.0.v.19.jar) 
	UCHIJA	UndergroundOcean{${version}} [Underground Ocean] (UndergroundOcean-1.1.0_develop_a69b2f0_alpha.jar) 
	UCHIJA	va{1.10.2-1.6.1} [Vanilla Automation] (va-1.10.2-1.6.1.jar) 
	UCHIJA	villagebox{0.6.0} [Village Box] (villagebox-1.10.2-0.6.0.jar) 
	UCHIJA	VTweaks{1.4.11.3} [V-Tweaks] (VTweaks-1.10.2-1.4.11.3.jar) 
	UCHIJA	waddles{0.5.4} [Waddles] (Waddles-1.10.2-0.5.4.jar) 
	UCHIJA	wallpapercraft{1.10.2} [WallpaperCraft] (WallpaperCraft-1.10.2-1.06.jar) 
	UCHIJA	wateringcans{1.1.2} [Watering Cans] (WateringCans-1.10.2-1.1.2.jar) 
	UCHIJA	waterstrainer{1.4.2} [Water Strainer] (WaterStrainer-1.9.4-1.4.2.jar) 
	UCHIJA	wearablebackpacks{1.7.0} [Wearable Backpacks] (WearableBackpacks-1.10.2-1.7.0.jar) 
	UCHIJA	weirdinggadget{1.0} [The Weirding Gadget] (weirdinggadget-1.10.2-1.0.2-universal.jar) 
	UCHIJA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.4.1.0.jar) 
	UCHIJA	wtfcore{1.10.2_v1.5} [WTFs Expedition-Homestead Edition] (WTFs_Expedition_Homestead_Edition-v1.10.2_1.6.jar) 
	UCHIJA	yoyos{1.10.2-0.2.0-5-} [Yoyos] (yoyos-1.10.2-0.2.0-5-.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	farseek{2.1} [Farseek] (Farseek-1.9.4-2.1.jar) 
	UCHIJA	harvesttweaks{1.10.2-0.1.2.DEV.9651204} [Harvest Tweaks] (HarvestTweaks-1.10.2-0.1.2.jar) 
	UCHIJA	hungeroverhaul{1.10.2-1.1.0.jenkins118} [Hunger Overhaul] (HungerOverhaul-1.10.2-1.1.0.jenkins118.jar) 
	Loaded coremods (and transformers): 
FarseekCoreMod (Farseek-1.9.4-2.1.jar)
  farseek.core.FarseekClassTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
ForgelinPlugin (Forgelin-1.5.1.jar)
  
LoadingPluginHardModeTweaks (HardModeTweaks-1.10-1.2.2.jar)
  com.hea3ven.hardmodetweaks.core.ClassTransformerHardModeTweaks
TANLoadingPlugin (ToughAsNails-1.9.4-1.1.1.19-universal.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
literalascension (literalascension-1.10.2-1.0.2.2.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
AstralCore (astralsorcery-1.4.5.jar)
  
AppleCore (AppleCore-mc1.10.2-2.2.2.jar)
  squeek.applecore.asm.TransformerModuleHandler
LoadingPlugin (Bloodmoon-MC1.10.2-1.5.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
SPFMLLoadingPlugin (soundphysics-mc1.10.2-v1.0.0.jar)
  com.sonicether.soundphysics.SoundPhysicsCore
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.9.jar)
  shetiphian.core.asm.ClassTransformer
DummyPlugin (ForgeEndertech-1.10.2-1.3.4.0-build.0057.jar)
  
Extra Alchemy ASM (extraalchemy-0.3.4-release.jar)
  zabi.minecraft.extraalchemy.asm.PotionTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.6.1.jar)
  org.blockartistry.DynSurround.asm.Transformer
BetterFoliageLoader (BetterFoliage-MC1.10.2-2.1.7.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
IvToolkit (IvToolkit-1.3.3-1.10.jar)
  
llibrary (llibrary-1.7.6-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BlurPlugin (Blur-1.0.3-13.jar)
  com.tterrag.blur.BlurTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 950/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	Pulsar/harvesttweaks loaded Pulses: 
		- blocks (Enabled/Forced)
		- items (Enabled/Forced)
		- tconstruct (Enabled/Forced)

	Launched Version: 1.10.2
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-6100 CPU @ 3.70GHz
	OptiFine Version: OptiFine_1.10.2_HD_U_E3
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 950/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

I dont know what to do at this point and I cant see any other forum posts about this anywhere.

**Comment by WesCook** [comment]
Hi there,

You're running out of memory, so the pack isn't able to completely load.  If you're able, I'd suggest allocation additional memory inside ATLauncher.  Remember to leave 1-2 GB for your operating system, though.

If you don't have enough memory, then unfortunately your computer isn't able to play the pack.
