### ISSUE TITLE
HarvestTweaks - Broken tools ignore harvest levels

### ISSUE THREAD

**Issue by Obreaks** [WesCook/Homestead#26]
u can mine everything by using broken tools...
![2017-08-07_13 19 32](https://user-images.githubusercontent.com/30797717/29024618-373df202-7b73-11e7-9b8f-f97bf5faf0ba.png)
![2017-08-07_13 19 35](https://user-images.githubusercontent.com/30797717/29024617-373d1dd2-7b73-11e7-98fe-21460c6055d6.png)
![2017-08-07_13 19 38](https://user-images.githubusercontent.com/30797717/29024619-37426ec2-7b73-11e7-88f0-db6792e9678c.png)

**Comment by krzys189** [comment]
This however is a major bug

**Comment by WesCook** [comment]
Thanks for the report.  Apologies for the delay in responding, but I didn't recognize the severity of the bug when I first read the description.

I've done some testing and reported this issue to the mod author, who hopefully is still maintaining the mod.

**Comment by WesCook** [comment]
boni has identified and corrected the issue.  The fix will be included in the next version.

**Comment by WesCook** [comment]
This bug has been corrected in Homestead v1.6.0.  Thanks again for the report!
