### ISSUE TITLE
bug with crossbow

### ISSUE THREAD

**Issue by Obreaks** [WesCook/Homestead#27]
shooting animation is broken
![2017-08-07_13 23 48](https://user-images.githubusercontent.com/30797717/29024810-145dc446-7b74-11e7-831e-16ecb8f605f6.png)

**Comment by krzys189** [comment]
I don`t think this is a bug

**Comment by WesCook** [comment]
Could you clarify how the animation is broken?  I can see that the bow icon jumps around somewhat while firing, though it seems relatively minor.

From your screenshot it appears to be glowing.  Is this related to the bug report?

**Comment by WesCook** [comment]
Closing due to lack of followup.
