### ISSUE TITLE
Pumpjack can`t be built.

### ISSUE THREAD

**Issue by krzys189** [WesCook/Homestead#29]
To build the pumpjack you need treated fences. But, treated fences have gravity on them, and because of that they just fall on the fluid pipes and break, making the pump jack unbuildable.

**Comment by WesCook** [comment]
Thanks for letting me know.  I'll fix that in the next version.

In the mean time, you may be able to place regular wooden fences nearby to hold them up.  They have a 3x3 retaining effect around themselves, on the same level and one up.

**Comment by WesCook** [comment]
This should be resolved in Homestead 1.5.0 as just released.  Sorry for the delay on this one, and thanks again for the report.
