### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by krzys189** [WesCook/Homestead#30]
After a while of playing my screen completley blacks out (not my whole monitor, just the minecraft)
it does the same when im underwater. It goes back to normal when i kill myself in game.

**Comment by WesCook** [comment]
It may be related to #9.  Could you try my suggestion from that issue to see if it has any effect?

If you can work out which mod is specifically causing it, I can put a warning up for that mod, or mark it as opt-in instead.

My top guess would be Enhanced Visuals though.  That applies a shader effect when underwater, and when you get too hungry.  This might explain why it seems to happen randomly after a while.

**Comment by krzys189** [comment]
Thanks! I will see if turning off the mods will fix it.

**Comment by WesCook** [comment]
I'll close this for now due to lack of response, but please update me if there's been any changes from the suggestion above.  Thank you.
