### ISSUE TITLE
Client not loading?

### ISSUE THREAD

**Issue by LoliShark** [WesCook/Homestead#31]
Recently I have purchased a windows laptop, previously running Mac, thinking it would work much better to run the games I want to run. However, when it came to playing the Homestead instance from the AT Launcher, it doesn't load. 

I should specify, the client loads up the instance, does all the mod initialising and gets to stage 7, but cuts out just before the client is playable and goes to the main Minecraft screen. This was not a problem on my Mac but it is here, and has remained through two updates.

I was wondering if anyone else has found a similar error, and if there was an easy fix that doesn't require trawling through logs. There doesn't seem to be a specific error or anything, as in, nothing is red near the end of the logs.

Kind regards,

LoliShark

**Comment by WesCook** [comment]
Typically when the launcher cuts out during loading, it's a memory issue.  But if it's right at the point that the game should load, there may be something else going on.

Could you upload a copy of your crash log so I could take a look?

**Comment by LoliShark** [comment]
No problem for me, the log is from starting up the AT Launcher and only trying to open the instance:

http://paste.atlauncher.com/view/092d3973

**Comment by WesCook** [comment]
It looks like you're running out of memory.  You're only allocating 1GB of memory to the pack, and it will require much more to run (I'd suggest at least 4GB, up to 6GB).  Remember to leave 1-2GB for your operating system to run as well.

If you don't have enough memory for the pack, then unfortunately there will be no way to play.
