### ISSUE TITLE
maybe bug maybe feature i didn't know about

### ISSUE THREAD

**Issue by vastrallakas** [WesCook/Homestead#32]
there are lava crust blocks appearing all around my base, they sometimes replace other blocks, sometimes appear in formations of their own.  i tried looking thru the mods and couldn't seem to find an explanation, so i thought i'd ask here.  if this is not a bug i'm sorry to take up your time, thanks for the help :)

**Comment by WesCook** [comment]
Hi,

There are caves with lava-encrusted stone blocks.  Is this what you mean?  They shouldn't be appearing after an area has already been fully generated though.

If you could post a screenshot, that would be helpful.  You can also hold crouch while looking at them to identify the block, and the mod they're from.  My guess is these are from WTF's Expedition.

**Comment by vastrallakas** [comment]
![2017-08-16_12 47 50](https://user-images.githubusercontent.com/31039770/29377921-f1c8107e-8282-11e7-99cd-5553c08428f2.png)
![2017-08-16_12 47 58](https://user-images.githubusercontent.com/31039770/29377936-f8e54458-8282-11e7-901b-34a8c6e00cf6.png)
 thank you for replying, the lava encrusted stone blocks are from WTF's expedition, they appeared and replaced blocks that were already there, mostly dirt.  I did fine a deposit like the mossy cobble deposits in forests, but instead of mossy cobble it was the blocks with lava inside from WTF's expeditions.  thank you for you time, hope you have a wonderful day

**Comment by WesCook** [comment]
Thanks for the update.  I'm honestly not sure what could be causing that.  It's possible Expedition is getting confused over if it's supposed to be generating moss or lava, though that doesn't explain why it's happening so late.

I do know that, for performance reasons, Expedition queues up its actions when generating new chunks.  So if you were to fly very quickly across the terrain you might see things popping in like this.  However, that should catch up relatively quickly.  You shouldn't have time to create a base first before blocks start popping in.  So I'm really at a loss.

Unfortunately I don't have a fix to suggest.  It's the first time I've seen this reported.  It sounds like it might be an issue with the mod itself, which WhiskyTangoFawks would need to take a look at.  Currently he's on a break though.

I can only suggest being very careful when breaking lava-encrusted blocks, and apologize for the unintended effect.

**Comment by vastrallakas** [comment]
oh, is fine, i was just wondering if i should expect any other wonky behavior or things that would break my world.  thanks for your time and consideration, hope you have a nice day :)

**Comment by WesCook** [comment]
Haha, not any other wonky features that I know of.  If there is, just let me know.

On the plus side, free lava for your smeltery.

I'll close this issue for now, as there's nothing actionable I can really do.
