### ISSUE TITLE
Unexplained black screen?

### ISSUE THREAD

**Issue by NoItsBecky** [WesCook/Homestead#33]
So, I'm really liking this modpack. Great premise, fun gameplay, and the quest book makes it so things actually make sense. Unfortunately, I've hit a huge issue--after some time playing in a world, the screen goes completely black. I'm not just talking about the gameplay; the chat and pause menu go black as well. I may as well be blind. It only happens with this modpack. It happens with every world. Is there an explainable reason for this?

**Comment by WesCook** [comment]
I've seen this issue a couple times now (#9).  Could you try disabling Enhanced Visuals (from the reinstall pack feature) and see if that has any effect?  I have a theory that this is happening after the player gets very hungry, which applies a shader effect.

**Comment by crashoverride81** [comment]
same problem here but full hunger and full thirst! did the fix suggestion here and still a problem1

**Comment by ILove07Gold** [comment]
I have this same exact issue! It happened after i played for about 1-2 hours, and the whole screen goes black. I read the logs and I geet some errors with railcraft and some missing textures from optifine. But those problems would have happened sooner.

**Comment by WesCook** [comment]
Thanks for the update.  If disabling Enhanced Visuals has no effect, could you also try disabling Mo' Bends, as discussed in #9?  If I can confirm that mod is causing this issue, I'll leave it disabled by default in the next version.

Thank you.

**Comment by ILove07Gold** [comment]
Disabling mo bends and enhanced visuals solved it for me. I recommend that you (modpack dev) remove both of these mods from the suggested list to prevent further problems.

**Comment by WesCook** [comment]
@ILove07Gold: Was it required to remove both mods to resolve the problem, or was removing Mo' Bends enough?  I'd like to be certain so I can put up adequate warnings.

@crashoverride81, I'd also appreciate if you could try to reproduce the fix for confirmation.

Thank you.

**Comment by crashoverride81** [comment]
okay so disabling the two mods fixed the problem for me!

**Comment by WesCook** [comment]
Thanks for the update.  Just to confirm, did you test if both mods needed to be removed to solve the problem?  Thanks.
