### ISSUE TITLE
Sophistiacted Wolves not rendering when rejoining a world.

### ISSUE THREAD

**Issue by tifkat** [WesCook/Homestead#35]
Playing on SMP server. A wolf was tamed by Player A and then given a treat and became sophisticated. Rendered ok for Player B. Player B Tamed a vanilla wolf and left it vanilla. Ended gaming session. Player B came back later, vanilla wolf renders, but sophisticated wolf does not. Entity shadow is present, and the 'tidy plates' floating info shows, the one probe shows a non-localised name in the info. Sneaking shows the owner of rht sophisticated wolf.

Player B fed the vanilla tamed wolf a treat, and it disappeared for Player B also. Entity shadow shows, 'tidy plates' info shows, the one probe shows non-localised name. Shift shows owner.

**Comment by WesCook** [comment]
Thanks for the great report.  Very detailed.  I noticed this bug myself in an earlier playtest, though for me (the owner), they were always visible.

Unfortunately this is more of a mod issue, so it's not something I can address from the pack itself.  This looks to be the relevant bug on the mod's issue tracker.

https://github.com/NightKosh/Sophisticated-wolves/issues/35

I'm going to close this issue for now as it's not something I can address, but if the mod is updated I'll include it in the following pack update.

Cheers.
