### ISSUE TITLE
planks and gravity

### ISSUE THREAD

**Issue by LaVidaYokel** [WesCook/Homestead#36]
I love the mod-pack but I really dislike that wooden planks are affected by gravity.  At the very least, planks placed adjacent to supported planks should stay attached to them, I think. Aside from being difficult to build with , it seems to be breaking the Saw from Better with Mods' ability to turn them into Siding; instead of being cut-up, the planks just fall to the side, unchanged.

**Comment by WesCook** [comment]
I'll consider changing this in the next version, thanks.

For the record though, the saw can be used on its side to cut planks.  They will only fall if it's placed facing upwards.  I see that this can be unintuitive behavior, though.

**Comment by LaVidaYokel** [comment]
Sideways!  How funny; yeah, I would have never of thought of that.  Thanks for the response!

**Comment by WesCook** [comment]
This should be resolved in Homestead 1.5.0 as was just released.  Thanks again for the report!
