### ISSUE TITLE
Arc Furnace and Distillery Tower not buildable

### ISSUE THREAD

**Issue by JWB2469** [WesCook/Homestead#37]
Cannot build the arc furnace because the Reinforced Blast Bricks are affected by gravity.

**Comment by WesCook** [comment]
Whoops, didn't consider that.  Thanks for the heads up!

edit: In the mean time, you could try placing fences on the outside to offer supports.  Though I'm not sure if the structure allows that.

**Comment by JWB2469** [comment]
We were able to work around it with fence.  Not sure if you want me to open up a different ticket but it is the same thing with the Distillery Tower, the steel scaffolding is falling if not supported by fence.

**Comment by WesCook** [comment]
That's okay, this ticket will suffice.  Thanks for pointing that out too.

I made the mistake of testing these in creative mode, where gravity doesn't take effect.

**Comment by WesCook** [comment]
This should be resolved in Homestead 1.5.0 as was just released.  Thanks again for the report!
