### ISSUE TITLE
Cow quest should explain how premium/regular milk is obtained

### ISSUE THREAD

**Issue by dpmcg89** [WesCook/Homestead#38]
Hello,

I'm not sure if this is a bug, or if there is a better way to get Animania milk.  So here's the deal:

1. Make a bucket with the classic recipe to get vanilla Minecraft bucket
2. Use that bucket on a Holstein or Friesian cow to get vanilla milk bucket
3. Fail to make cheese since cheese recipe requires Animania milk bucket + cheese mold
4. Pam's Harvestcraft fresh milk does not work either

I tested things in Creative and it looks like there is no way to get the breed-specific Animania milk required to make cheese.

I think if you tweaked the recipe for cheese to allow Pam's HC milk or vanilla Minecraft milk to combine with the cheese mold, that would fix it (you could just pick a cheese for them to make.  I'm not sure if it matters what breed the milk is from).

**Comment by dpmcg89** [comment]
Ok, weird.  I see you have

> // Milk compatibility
<ore:listAllmilk>.add(<minecraft:milk_bucket>);
<ore:listAllmilk>.add(<animania:friesian_bucket_milk>);
<ore:listAllmilk>.add(<animania:holstein_bucket_milk>);

in cooking.zs  I'm not sure why this isn't working for me.

I see that the problem is the milk I'm getting from the cows.  In my private creative world it comes out with the proper breed-specific Animania milk when you right click on a cow with a bucket.  Good to go on the cheese front.  On my server it is always vanilla Minecraft milk.  Weird.

**Comment by WesCook** [comment]
The difference is likely that the cows in your testing world are happy, and giving premium milk (which can be made into cheese).  The cows on your server don't have the right conditions to be happy.

You can check for dark particles to see if they're upset, or hold crouch to see if the cows have Weakness applied.

**Comment by dpmcg89** [comment]
Ohhhh that's definitely it.  They've all got crazy weakness.  I didn't realize that was a feature.  Ok nice.  Sorry for the trouble.

**Comment by WesCook** [comment]
I can't check right now, but is this mechanic explained in the quest book entry for cows?  If not, I'll be sure to add a proper description for the next version.

Thanks!

**Comment by dpmcg89** [comment]
I remember you mentioning that animals have degrees of happiness 

> An unhappy animal won't breed or produce many resources

But yeah, I agree this could be a little clearer.

I feel ashamed though.  I've outed myself as a terrible farmer with unhappy cows. T.T
![2017-09-05_14 56 30](https://user-images.githubusercontent.com/30128840/30078358-ef0b545e-924a-11e7-9eb6-68ff9de68172.png)
![2017-09-05_14 56 34](https://user-images.githubusercontent.com/30128840/30078359-ef0bb818-924a-11e7-9e50-accbf994e534.png)
![2017-09-05_14 56 49](https://user-images.githubusercontent.com/30128840/30078356-ef07184e-924a-11e7-88e8-9c09604d1de2.png)
![2017-09-05_14 57 15](https://user-images.githubusercontent.com/30128840/30078357-ef09fafa-924a-11e7-9844-5a48db21f71b.png)

**Comment by WesCook** [comment]
Okay, agreed.  I'll leave this issue up as a reminder to update the text.  Thanks for bringing that to my attention.

Now go give your moo cows a hug.

**Comment by WesCook** [comment]
I've updated the quest description in Homestead 1.5.0.  Thanks again for the report.
