### ISSUE TITLE
Planks, fences, and scaffolding are no longer affected by gravity 

### ISSUE THREAD

**Issue by Hawke** [WesCook/Homestead#39]
Building a structurally-sound house is way more fun.

**Comment by WesCook** [comment]
I agree, but sadly it led to some bugs with creating multi-block structures that I needed to address.  Planks also had a buggy interaction with saws when they were placed upright.

These were the entries I removed from the gravity list in the latest version, if you'd like to add them back.  They cover all sub-IDs for these blocks as well.

https://github.com/WesCook/Homestead/commit/619561fd69fbb66605b5b91f01296d2d71c558af#diff-a1c535eb0cfc37124a6ee9d21674dbb4

Unfortunately I need to close this issue as it was an intended change.

**Comment by Hawke** [comment]
I figured as much. I mostly just wanted to quote the changelog as an issue. ;-)

Fences and scaffolds are fine unaffected by gravity; if I recall fences already were (or are they considered planks) and scaffolds already have built-in limitations.

Is there any possible workaround that could be done to counter the effects of gravity while still keeping the fun? (I have no idea what the mod in question has if anything but I could imagine using hammer/nails or pegs to attach planks together horizontally)

**Comment by WesCook** [comment]
Regular fences were previously unaffected, though Immersive Engineering fences ("woodenDecoration") had gravity applied.

The only method to counter the effects of gravity were vanilla fences on an adjacent block.  However the behavior would still be too unintuitive for many players, I'm afraid.
