### ISSUE TITLE
Why are there so many items that aren't allowed in the portable bag?

### ISSUE THREAD

**Issue by LaVidaYokel** [WesCook/Homestead#40]
I get why a ladder wouldn't be allowed, but there seem to be a lot of items that it won't hold, why is that?  The backpack didn't have these limitations.

**Comment by WesCook** [comment]
I didn't think I put any restrictions on the portable bags.  These are the configs:

https://github.com/WesCook/Homestead/blob/619561fd69fbb66605b5b91f01296d2d71c558af/config/bagginses/bagginses.cfg#L31-L51

Could you give a general list of items which aren't allowed?  I may have misconfigured the mod.

**Comment by LaVidaYokel** [comment]
I don't know how I didn't notice this before; it's only accepting vanilla items.   Items from other mods display the message "This item is not allowed in this bag." in their tooltip when the bag is open.   


I checked my config and it's only got a wildcard, no modid's, in the whitelist.

**Comment by WesCook** [comment]
Okay, thanks for the heads up.  I'll see if I can make it accept any item in the next version.

**Comment by WesCook** [comment]
This bug has been corrected in Homestead v1.6.0.  Thanks again for the report!
