### ISSUE TITLE
Optifine doesn't let me get "in-game"

### ISSUE THREAD

**Issue by Hierophann** [WesCook/Homestead#41]
Hello! I've encountered an odd bug with optifine. 

Everything loads up correctly, I select a world, start loading, enter the game, and then, it just seats me in the pause menu; that's it!

The game becomes super laggy, and the buttons take like 5 seconds to get highlighted by the cursor. Removing optifine alone lets me enter the same world.

Is there anything you know about this? Optifine is almost needed for me to enjoy the game at decent-good framerate. 

Thanks!

**Comment by WesCook** [comment]
I've not seen this issue reported yet, nor have I experienced it myself.  What I would suggest is disabling every configurable feature of Optifine from the menu, just to see if any one specific feature is causing this.  If so, you can work backwards to figure out which feature it was, and disable only that one in the future.

If Optifine as a whole is causing this, then I'm afraid I don't have any suggestions.  You may need to test the pack without Optifine to see if it's still playable for you.
