### ISSUE TITLE
requesting a way to light Immersive Craft furnace, pre-iron.

### ISSUE THREAD

**Issue by LaVidaYokel** [WesCook/Homestead#43]
The Immersive Craft furnace fits-in with the pack really well but there's no reason to use it.   Adding a way to light it prior to acquiring the iron ingot needed for the flint and steel (not to mention the vanilla furnace) would be awesome.

**Comment by WesCook** [comment]
The immersive furnace was actually required in my original version of the tech tree.  Eventually I did remove it though as I had trouble integrating the flint and steel into earlier game, and I opted to use fire charges instead.

I am happier with the current tech tree than I was with the original, but I agree it makes the immersive furnace a bit useless.  You can craft it, but not light it until later.

If it were compatible with fire charges, that would be a good option for early food cooking, but I don't believe it is.  So for now it remains more of a novelty.

**Comment by LaVidaYokel** [comment]
Thanks for the response. Oh well!
