### ISSUE TITLE
Balancing Issue, Creating Metal out of thin air

### ISSUE THREAD

**Issue by Fitzgerald93** [WesCook/Homestead#45]
Iron and steel rods should have their smelting values reduced to 36mb as in its current 72mb state you can use 1 ingot in a metal press make 4 rods and resmelt them creating 2 ingots.

**Comment by WesCook** [comment]
Thanks for the report on this, and sorry for the delay in getting back to you.  I'll address this in the next modpack update.

**Comment by WesCook** [comment]
I've addressed this in the just-released Homestead v1.7.  Thanks again for your report.
