### ISSUE TITLE
Fish trap & Impossible quest

### ISSUE THREAD

**Issue by vamoosi** [WesCook/Homestead#47]
Hey, two issues --

First of all, I was thinking about making a water trap in my game in hopes that I could get some jellyfish for slime, since I haven't seen any slimes out in the wild. But in order to make one of those you have to be able to make a vanilla fishing rod, which is impossible in the current homestead build. It also seems like it only takes vanilla chests but I don't know if that'll be an issue per se.

Second, I know that refined relocation was taken out of the modpack, but there's still a quest under Home Life that requires you to make a refined relocation chest. That's pretty whatever in the long run I guess but I like the completionism aspect of the quests.

edit: actually looking through the files it looks like the quest in question was removed but i'm just stuck with it in my game unless i wanna start a new file? so ... alas

**Comment by WesCook** [comment]
Hey there,

Thanks for the heads up on the fishing pole recipe.  I'll look into that.

On the impossible quest, have you updated your quest data from a previous Homestead version?  That info is stored in your world folder, so I can't update it automatically unfortunately.

Here's the steps to update your questing info:

>Note: Existing worlds will not automatically receive quest changes on pack updates. On clients, you can run `/bq_admin default load` as an op to update existing worlds. On servers, please copy the file `/config/betterquesting/DefaultQuests.json` over `/world/betterquesting/QuestDatabase.json`.

**Comment by vamoosi** [comment]
That worked out fine! I had to open up to LAN and enable cheats but that's not a problem at all. Thanks!

**Comment by WesCook** [comment]
I've updated the recipes with fishing rods in Homestead v1.7.  Thanks again for the bug report!
