### ISSUE TITLE
black screen after playing

### ISSUE THREAD

**Issue by bloodvampire16** [WesCook/Homestead#48]
well it started on a friends open land world where i played for a good hour then went mining in a ravine then my whole screen went black i couldnt even see the pause screen buttons but they were still there when i exited the world it went right again but apon going back in it was black and i tested it in single player world and after a few minutes it started going black on me there as well :I

**Comment by WesCook** [comment]
Hey, thanks for the report.

From what I've seen of this issue, I believe I have it narrowed down to one of two mods.  Could you try disabling each of these mods in turns and seeing if it solves the problem?

The mods are "Enhanced Visuals" and "Mo' Bends".  These can be disabled by reinstalling the pack in ATLauncher.

I'd like to know exactly which one is at fault, so if you could try disabling them one at a time first, that would be appreciated.

Thank you.

**Comment by bloodvampire16** [comment]
will do wes though ill just take out the mod then try if it still happens we shall know cause i added project e and inventory pets to mine so i cant reinstall :P

**Comment by bloodvampire16** [comment]
wes its the enhanced visuals i noted that with it in when i went under water it would make my screen black briefly now it doesnt do that so ya i think i found ur culprit

**Comment by WesCook** [comment]
Thanks for the update.  I'm going to have that mod disabled by default in the next version then, to try and prevent this black screen issue.

I'll leave this open for now so I don't forget.

**Comment by bloodvampire16** [comment]
kk im glad i could help i love ur modpack so far well what i could play of it before the black screen stoped me im glad i can resume it

**Comment by WesCook** [comment]
I've added a notice and made Enhanced Visuals disabled by default in Homestead v1.7.  Thanks again for checking into this for me.
