### ISSUE TITLE
Reactivate vanilla and reduce break block

### ISSUE THREAD

**Issue by darknat** [WesCook/Homestead#5]
hi I've download HomeStead modpack, but i want to reactive vanilla tool ( i want to use axe to harvest trees..) and when i break a block, it is very slowly, what is the mod ?)

Thank you,

ps : sorry for my little english :/ and sorry isn't a true issues but i haven't find the solution and you modpack is very cool.

**Comment by WesCook** [comment]
Well, enabling vanilla tools will affect progression but it can be done by editing `/scripts/tools.zs`.  Remove the code under "Disable Tools" for the desired tools.

Regarding block break speed, this is to discourage branch mining.  It can be modified by editing `/config/WTF-Expedition/WTFStoneRegistry.cfg`.  Set the "Percentage speed modifier" for each entry that you'd like to affect.  Setting each value to `100` will disable the effect entirely.

Note also that different rock types have different breaking speeds.  For instance Igneous rocks break very slowly, while Sedimentary and Metamorphic rocks will break more quickly.  It's possible you're digging in a biome with harder rocks.

**Comment by darknat** [comment]
Thank you, because I add "villagebox" mod's and it use vanilla tools. 

Ok, i see that, and i think you have reason. maybe I digging in a biom with harder rocks.

But thank you very much, your modpacks is very very good, i like it.

**Comment by WesCook** [comment]
Thanks for the kind words regarding the pack.

I'm a bit confused by your comment though.  Village Box is actually already in the pack, and I've customized the trades to remove the dependence on vanilla tools.  Have you added it to the pack again, or am I misunderstanding you?

**Comment by darknat** [comment]
Oh, but in don't see, i just read in a forum that villagebox use vanilla tools. But it is also because i don't understand everything with flint mod and tinker, i can't harvest tree with tinker or vanilla. I see when i'm my home.

**Comment by WesCook** [comment]
The Flint Hatchet should allow you to harvest trees, and it can be made using just flint and sticks (dropped from leaves).  The quest book is there to step you through the new tech tree.

Tinkers tools can then be created to make more advanced tools.

If you're playing on a server, it's possible that spawn protection is also preventing you from harvesting a tree.  You'll need to be outside of the protection range to harvest blocks in this case.

**Comment by darknat** [comment]
Yes, but i can't harvest some tree like coconut tree and I remove " disable tools" in tools.zs but doesn't work. 

EDIT : hmmm not work only on multiplayer i don't understand..

**Comment by darknat** [comment]
I delete map and recreate it's good, vanilla tool work, but no tinker hatchet ...

**Comment by WesCook** [comment]
If you're playing on a server, you'll need to make these changes on both the client and server.  Simply editing it on the client side would allow players to cheat, so that isn't possible.

The Tinkers hatchet is constructed in the normal way using the Tool Station and any accessible material (eg. bone, flint, cactus).  The Quest Book and Tinkers Construct book may assist you here.

**Comment by darknat** [comment]
Obviously, I changed the client and the server.

And for the tinker's axe I will continue the adventure see if it always blocks. However in creative, the hatchet  of wood / stone / bone does not allow to cut the trees.

**Comment by WesCook** [comment]
Blocks won't drop in creative mode.  You'll need to be in survival for tools to be effective.

Also note, wood and I believe stone are very low tier.  Cactus, flint, or bone tools are required to begin harvesting things.

**Comment by darknat** [comment]
Okay thank you.

It's good, I understand, but a new problem with stick and campfire to create torch, doesn't work :/ ? it's campfire of tough as nails ?

**Comment by WesCook** [comment]
Yes, that's right.  Using sticks on campfires will ignite it, eventually.  Because it's a random chance it can often take many sticks.

Once ignited, sticks can be used on the lit campfire to instead make torches.

**Comment by darknat** [comment]
Okay ! It's good now sorry i'm newbie .. and now I have another problem ... with better quest , can't work I have this message on my server : Recieved a packet server side with an invalid ID bq_stantard:checkbox for the first quest.

quest doesn't work, I try to copy defaultquest and my world save but no.. ( it is au newworld)

**Comment by WesCook** [comment]
That shouldn't be happening...  That error message triggers when a quest ID is less than 0, and the quest ID is 61.  My only guess is that there's some desync between the client and server, such as if the config files weren't installed the same on both.

To properly debug that error we'd need to review all the possible variables that might be in play.

**Comment by darknat** [comment]
Hmm, config of better questing client and server are the same.. I delete a world, create etc.. nothing and config is all the same.. 

What is all folder of betterquesting ?

EDIT  : another erreur : Tried to load missing task type 'bq_standard:checkbox'! Are you missing an expansion pack?

**Comment by WesCook** [comment]
>What is all folder of betterquesting ?

I'm sorry, could you clarify the question?

>Are you missing an expansion pack?

This might indicate that the Better Questing - Standard Expansion mod isn't installed.  It should be included with the client and server downloads.

**Comment by darknat** [comment]
> What is all folder of betterquesting ?
> I'm sorry, could you clarify the question?
forget this lol

alright ! missing Better Questing - Standard Expansion I don't understand why and how .. now is it good !

**Comment by WesCook** [comment]
Glad to hear.  I'll mark this as closed now as the problems above have been addressed.
