### ISSUE TITLE
Big fault took too long. 

### ISSUE THREAD

**Issue by PoppaRufus** [WesCook/Homestead#50]
I found that it took way too long to get goats in there. I was promised many odd months ago to get goats. I have not seen any goats. But now we have goats, So i can start my goat farm. This is not Rufus.

**Comment by WesCook** [comment]
You're absolutely right.  The lack of goats was a failing on my part.  Fortunately ~Goat Sim~ Homestead can now be considered a genuine modpack offering much in goat-farming potential.
