### ISSUE TITLE
Allow bricks for floors?

### ISSUE THREAD

**Issue by Svish** [WesCook/Homestead#51]
I've always liked to use bricks (for example smooth stone bricks) for floors between, well, floors... But in this modpack, not that I've come very far yet, I've only been able to use wood, because everything(?) else just falls down when I try to put it up. So...

1. First of all, what is the mod that adds this feature?
2. Would it be possible to maybe add "unnatural" blocks, like bricks, to the list of "unfalling" blocks?
3. And regardless of 1 and 2... *is* there a way to create multiple floors in this modpack without wood?

**Comment by Mac15001900** [comment]
You can go to _config/WTF-Expedition_ and edit the _WTFGameplay.cfg_ file. It has a list blocks affected by gravity, and you can just remove all unnatural ones. 
Personally, I think that should be the default; while falling stone makes mining more interesting, I don't understand what do you gain from not being able to build a tent out of wool, or a roof from bricks.

**Comment by WesCook** [comment]
Thanks for the feedback.  In Homestead v1.7.1, more artificial blocks are unaffected by gravity, including bricks.
