### ISSUE TITLE
Storage Drawers?

### ISSUE THREAD

**Issue by Svish** [WesCook/Homestead#54]
Just discovered a mod called [Storage Drawers](https://minecraft.curseforge.com/projects/storage-drawers) on CurseForge towards the top of popular mods. Haven't tried it, but it does look very nice and, more importantly, quite... "Homesteady"? 🤓

Could always just try adding it manually myself locally, but just thought I'd suggest having it added to the pack as it looks so useful, popular, and fitting. 🙂

**Comment by WesCook** [comment]
Hey Svish,

Thanks for the suggestion.  I am actually familiar with Storage Drawers, and considered adding it (we are in need of a proper storage solution).  However I felt that mod was a bit too easy compared to most, and negated the need of [ImmersiveEngineering Silos](https://ftb.gamepedia.com/Silo).

As multiblocks are a big part of this pack, I liked the idea of using larger buildings for bulk item storage.

I'd still like to add some proper item sorting in the future, though haven't quite found a mod that accomplishes that task (and I've looked at most of them).

Thanks again for the suggestion though.  I'm always on the look for "Homesteady" mods that will fit in.

Cheers.

**Comment by Svish** [comment]
Hm, after looking at the IE Silo mod, I gotta say I disagree about "negat[ing] the need"... I'd rather say they serve two separate storage needs and compliment each other quite well.

* Storage Drawers for organizing your inside work shed.
* Silo for storing your grain and produce.

Of course, I suppose Storage Drawers *could* be used for ones produce too, but Silo looks more appropriate and cooler and more "Homesteady" for that. Would be weird with a lot of drawers next to my fields to store the wheat. 😛

If you want to "Questify" and force it a bit more (personally wouldn't mind that actually), maybe it's possible to disallow certain items in the drawers?

👍

**Comment by WesCook** [comment]
I appreciate that the aesthetics may be better suited to different tasks, though unfortunately most people will go with what they know.  Storage Drawers is a quite popular mod, and balance-wise is significantly cheaper than Silos.  I do think it would overshadow its immersive neighbor.

As for disallowing specific items, it's an interesting thought though I don't believe this is possible.  It may also lead to confusion if it breaks expected functionality for users (I would be anticipating bug reports on it).

That said, Homestead is meant to be expandable so I absolutely encourage you to add the mod to your world if you are interested in it.  I'm trying to keep the base pack somewhat trim, but am always happy to see people tweaking it in new and interesting ways.
