### ISSUE TITLE
can not relight campfire with sticks

### ISSUE THREAD

**Issue by crashoverride81** [WesCook/Homestead#56]
everytime the campfire goes out i have to break it to make a new one and cannot relight it with sticks..dunno if its a bug and a feature!

**Comment by WesCook** [comment]
Unfortunately this is a consequence of how Tough as Nails handles campfires.  There's no simple way for me to change this as a modpack developer.

You could create a feature request on [their Github page](https://github.com/Glitchfiend/ToughAsNails) if you'd like to see a way to relight campfires, though we'd be unlikely to get a backport to the 1.10 version.

So let's just say that once the wood has been burnt, it's lost all its fuel and some fresh wood needs to be fetched.
