### ISSUE TITLE
putting stuff in compost bin causing crash

### ISSUE THREAD

**Issue by crashoverride81** [WesCook/Homestead#58]
No matter what i put in the bin it crashes my game!

**Comment by WesCook** [comment]
Thanks for the report!  I've created an issue on the relevant issue tracker.

**Comment by WesCook** [comment]
While a proper fix will depend on the mod author updating, I've gone ahead and disabled the Compost Bin in Homestead 1.7.2.  It is uncraftable and now displays a warning on the tooltip.

I'll mark this as closed for now, but will revert this change if the mod receives a fix for this issue.

**Comment by WesCook** [comment]
Just as an update, I added the Compost Bin back in v1.8.0 as the bug was fixed.
