### ISSUE TITLE
Animania animals

### ISSUE THREAD

**Issue by AggressiveBomber** [WesCook/Homestead#59]
Hello! I have a problem with animania, I am unable to get any of the specific items that relate to the animal. Persay if I am attempting to slaughter a Holstein cow, it will simply drop regular steak and not the specific steak relating to stated animal. This goes for just about every animania animal out there, any help would be appreciated.

**Comment by WesCook** [comment]
If I recall, Holstein cows don't give special meats but instead offer special milk.  This is only if they're kept happy (and as of the recent patch, have already given birth).

Other animals also need to be kept happy to give their more premium drop, assuming they have one.  The best place to check for this is the [Animania Curse page](https://minecraft.curseforge.com/projects/animania).

**Comment by AggressiveBomber** [comment]
The only problem is that I also have Herefords as well and they don't drop anything special. I could be wrong but I'll go ahead and try improving my pens, I appreciate the link!

**Comment by WesCook** [comment]
I'd suggest jumping into a creative world and testing with freshly spawned animals, as they will be happy by default.  This should let you see if you're getting premium drops or not.

Also know to look for black smoke particles, and a weakness effect on the animals when they're unhappy.  In this state they won't grant premium drops.
