### ISSUE TITLE
Iron Ore placement is disabled, stops progression in Astral Sorcery

### ISSUE THREAD

**Issue by Joshposh70** [WesCook/Homestead#6]
The title is pretty self explanatory, in Astral Sorcery you have to use a lens and a source of starlight to turn Iron Ore into Starmetal ore, which is required for progression.

However; Iron Ore placement is disabled in survival mode (creative has no such issue) meaning you cannot progress.

Tested in SSP and SMP using the latest version Homestead.

**Comment by WesCook** [comment]
Thanks for the heads up.  Astral Sorcery was the one mod I knew very little about when adding.  I had hoped there wouldn't be any problems like this.

The inability to place ore is a result of WTF's Expedition.  Unfortunately to change this, I'd need to disable the ore fracturing mechanic.  I'll see if I can figure out a workaround, but may need to make a compromise there.

**Comment by WesCook** [comment]
I've opened up a request to have Whiskey fix this on his end, or to allow me to submit a pull request to add a config.  https://github.com/WhiskyTangoFawks/Expedition/issues/146

In the mean time though, I can only suggest digging a vertical mineshaft to iron, or placing it in creative.  I know that's not ideal, but at this point I don't believe it's worth giving up the ore fracturing mechanic.  I'm still open to consideration though if a strong argument can be made either way.

Again, thanks for reporting this issue.  I'm playing through Astral Sorcery now, so will hopefully be more familiar for future pack updates.

**Comment by WesCook** [comment]
I've released Homestead v1.3 with a forked version of WTF's Expedition that resolves this problem.  Hopefully it doesn't create any new problems!
