### ISSUE TITLE
Crash Loading chunks

### ISSUE THREAD

**Issue by vannucci16** [WesCook/Homestead#60]
hi having an issue where the server will crash loading chunks all we have added to the pack are
Journymap
Tombmenygraves

we also have sponge forge and a few plug ins
CatClearLag-0.8
ClearMob-2.0.0
MMCReboot-2.1.1-API-5.1-6.X
MMCRules-1.1-API-5.0.0
Nucleus-1.1.6-LTS-S5.1-MC1.10.2-plugin
NucleusMixins-0.25.2-5.1
permissionmanager-3.0.1

https://pastebin.com/2JD1JipU
here is the crash report

**Comment by WesCook** [comment]
I'm sorry, but I can't offer support for modified versions of the pack.  In particular, Homestead has not been tested with Sponge at all.  From what I've observed Sponge makes a number of changes that some mods are inherently incompatible with.

The crashlog suggests that Sponge is likely at fault, as `SpongeWorldGenerator` is leading to a NullPointerException.  I would suggest disabling Sponge and its plugins to see if that resolves the issue.

If you require Sponge, you're going to need to figure out which Forge mod(s) it's incompatible with.  Unfortunately this is unsupported territory.

But I wish you luck, and I hope you're able to enjoy the pack.

**Comment by vannucci16** [comment]
thanks for the input if nothing else it gives me a place to start Great pack so far by the way
