### ISSUE TITLE
Transparence

### ISSUE THREAD

**Issue by krzys189** [WesCook/Homestead#61]
So, i reinstalled the pack, turned off enhanced visuals aaaaand... everything seemed to be working fine, until i got an achievment. Basically what happens is whenever i get an achievment every solid block becomes transparent, which is both helpful and annoying. I am not sure what can be causing the problem and if its even a bug, but i decided to report it.

**Comment by WesCook** [comment]
Well it definitely seems like a bug.  I haven't heard this one yet, and unfortunately I don't have any ideas on how to fix it either.

I wonder if those who were affected by the EnhancedVisuals black screen problem are also susceptible to this.  My only guess is that your graphics card might not support a required OpenGL feature that is being made use of.

Either that, or a mod isn't cleaning up properly after itself.  Though if that were the case I would expect the transparency bug to be more widely supported.

The only suggestion I can think of would be to update your graphics card driver, and see if that has any effect.

Alternatively, you could try removing the achievements altogether by using a different mod.  This is completely untested but it's worth a shot if you'd prefer solving the glitch to having achievements available.

https://minecraft.curseforge.com/projects/no-more-achievements
