### ISSUE TITLE
Ardite and Cobalt ore disappears/is ignored when put into Crusher

### ISSUE THREAD

**Issue by Svish** [WesCook/Homestead#63]
Had the crusher going with some iron and copper ore. Threw in a stack of ardite and cobalt ore as well, but none of that came out again. Tried putting more ardite ore into it when the crusher wasn't going, and looks like it just lays there, without the crusher picking up on it being there. Which was better than it disappearing of course... but yeah... possible to add support for these?

**Comment by WesCook** [comment]
So there's actually no dust or grit in the pack that I can return for cobalt/ardite.  However in the next version it will return 18 nuggets instead, equal to 2 ingots.  Might mess up some production lines... but we'll call it a *feature* to be worked around.

**Comment by WesCook** [comment]
v1.8.0 is released with this change.
