### ISSUE TITLE
Player's Thirst not decreasing since the update

### ISSUE THREAD

**Issue by shucktech** [WesCook/Homestead#64]
I just updated my server and clients to Homestead_180, however it seems that the thirst level is no longer reducing for players. I double checked the 'tough as nails' config; https://i.imgur.com/XgKm2Rf.png and it seems to be enabled. 

Any thoughts as to another mod in the pack that might be overwriting this? Or other options to check? Thanks!

**Comment by WesCook** [comment]
I'll take a look.  Thanks for reporting it.

Looking at your screenshot briefly, I see that body temperature has been enabled.  Was that a change you made?  I hope I haven't accidentally enabled that globally.

**Comment by shucktech** [comment]
Wes, thanks for the response. It seems I might have forgotten to restart the server after making a config change. Thirst is now working. You can close this issue. Also, to answer your question, I did manually change the body temp setting. Your global/default setting was set to "false" 

Also, I know this is off topic, but I'd love to see some sort of food expiration added into this pack. Also to have pam's crops be affected by the winter months. Thanks for the great mod pack!

**Comment by WesCook** [comment]
No problem.  I'm just glad to hear I don't need to push a hotfix.

Thanks for the suggestions.  I'm not currently aware of any mod that adds a food spoilage mechanic.  I think I'd like that as an option if it were available (similar to body temperature), but perhaps not on by default.  That was always one of the features that frustrated me from TFC, personally.

Regarding Pam's not freezing in winter, I'm disappointed by that too.  There was an attempt at making the two work together, and it required custom builds of both TAN and Harvestcraft, but I don't think it went anywhere.

Unfortunately as we're on 1.10, this is quickly becoming unsupported territory.  We get the odd bugfix, but rarely new features.  So I'm not super hopeful to see this feature coming in the future, unfortunately.

If it ever becomes possible though, I'll definitely be adding it.
