### ISSUE TITLE
Cant make a market place

### ISSUE THREAD

**Issue by Loafcat** [WesCook/Homestead#69]
Hey guys,

Playing a server hosted by a friend and i cant seem to make a market place? I've tried various variations, was wondering if anyone had the answer to this it's literally driving me insane. Thanks

**Comment by WesCook** [comment]
There's a mod called Farming for Blockheads which has its own Market block.  The standard Pam's Harvestcraft Market has been removed in favor of it.

Is it the Pam's version you're unable to craft, or the Farming for Blockheads version?

**Comment by Loafcat** [comment]
Hey! 
Ive tried the recipe for both and tried them both on the normal crafting bench and the crafting station and neither recipe is working for me and producing a market. Ive tried the recipe with four wool, an emerald in the middle and four wooden planks/wood. And the farming foe blockheads one with the 4 pieces of wood, 2 planks and red wool!

**Comment by WesCook** [comment]
I'll look into it.  Thanks for the report.

**Comment by WesCook** [comment]
Oof, `blockWool` vs `wool`.  I can't believe that slipped through testing.

This will be fixed in the next version.  Thanks again for the report.
