### ISSUE TITLE
Iron duplication

### ISSUE THREAD

**Issue by jchen1210** [WesCook/Homestead#72]
When crafting buckets of slop, the bucket is not consumed and after pouring the slop out of the bucket you crafted, you keep the empty bucket so you end up with 2 buckets from 1. The buckets can then be smelted in a smeltery to duplicate iron.

**Comment by WesCook** [comment]
This is the bug that just won't die.  I must have inadvertently used some old script files that didn't include this fix.

Will be fixed in the next version, thanks.
