### ISSUE TITLE
Better With Mods + Better Foliage unintended interaction

### ISSUE THREAD

**Issue by Sagragoth** [WesCook/Homestead#75]
The detector block in better with mods does not detect transparent blocks.  Better Foliage causes tree logs to be seen by the detector as transparent.  This cripples some automated tree farm designs.

**Comment by WesCook** [comment]
Thanks for the report.  Though, Better Foliage is a client-side mod only.  I'd be very surprised if it was having any effect on the detector block running server-side.

You could test this without Better Foliage installed to verify.  Though to be honest, I don't think there's anything I could do to resolve this issue without sacrificing existing features.
