### ISSUE TITLE
Grapling hook in water gives super swimming speed. 

### ISSUE THREAD

**Issue by Inf0214** [WesCook/Homestead#78]
If you sue any grapling hook in water you can move really fast, like speed hack fast. Is there any way to fix this or should I just consider it speed hack and throw in antihack that kicks players that move too fast?

**Comment by WesCook** [comment]
Hey, thanks for the report.  This is an issue I'm aware of, but unfortunately I don't have any way to fix it.  It's something the mod author would need to address.

The grappling hooks are from this mod: https://minecraft.curseforge.com/projects/grappling-hook-mod

Also I think this may be the relevant bug report on their tracker: https://github.com/yyon/grapplemod/issues/19

An anti-cheat mod may solve the issue, as you suggested.  You could even try re-enabling the "moved too fast" check (which is disabled by [mtqfix](https://minecraft.curseforge.com/projects/mtqfix)).

Sorry there's not much else I can do.  As this isn't actionable from my end though I'm going to close this issue.  Hopefully you find an approach that works for you.

**Comment by Inf0214** [comment]
Thanks, I knew you probably wont be able to do anything, just wanted to point it out :)
