### ISSUE TITLE
Pickaxe realy slow on some rocks. 

### ISSUE THREAD

**Issue by Inf0214** [WesCook/Homestead#79]
I made an Iron pickaxe and some of the underground rocks are slow to break, also it works really good on dirt gravel ect. It is strange because I augmented the pick for mining speed but it didnt make it any faster.  ( the pick was made with the Tinkers' Construct )

**Comment by WesCook** [comment]
There's a good chance you're mining igneous rock, which is very tough.  You can check the hover tooltip on the rock to see what type it is.

Iron isn't a particularly high tier in the pack so it will still be rather slow.

The best way to mine ores in this pack is to quickly navigate caves.  Branch mining will be much less effective than other packs.
