### ISSUE TITLE
[Slurp] Recent Tough As Nail Udate

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [WesCook/Homestead#81]
Hi WesCook, I noticed you are using my Slurp mod in your pack, (Thank you!) however in a recent Tough As Nails update this broke the mod. Already talked to the devs to see if they can hopefully fix it soon. I would suggest using an older version before the 1.10-1.12 merge

**Comment by WesCook** [comment]
Hey Epic,

Thanks for the heads up.  Are `slurp-1.10.2-0.3.jar` and `ToughAsNails-1.9.4-1.1.1.66-universal.jar` still incompatible?  Both versions are from a few months ago, so I'm not sure if the pack would be affected.

The only bug I remember coming across was that Slurp didn't work if the cursor could reach a block.  Though I explained it away in lore ("requires deep water to drink"), so it wasn't a huge issue.

Appreciate you reaching out.

Cheers.

**Comment by EPIICTHUNDERCAT** [comment]
HAHA! love the cover up. and no problem. those older versions should be cool
