### ISSUE TITLE
tcon Lumber Axe conflict with chopdown

### ISSUE THREAD

**Issue by Toksyuryel** [WesCook/Homestead#84]
Rather than breaking the whole tree like it is supposed to, chopdown overrides the lumber axe and causes the tree to fall over and only the block chopped to break.

**Comment by WesCook** [comment]
Hey,

Thanks for the report.  It's a known issue, but unfortunately there's not much I can do on my end to improve compatibility.  This issue existed with the previous mod I used as well, [TimberJack](https://minecraft.curseforge.com/projects/timberjack).

If you'd like to see compatibility added, you could try ChopDown's [bug tracker](https://github.com/ternsip/ChopDown/issues) and hope they decide to add support.  The mod hasn't received any updates or commits in six months though, so realistically I don't think it's too likely to happen.

Here's hoping though.  If they release any updates, I'll certainly include them in the pack.

**Comment by Toksyuryel** [comment]
In that case, would it be safe for me to disable the mod?

**Comment by WesCook** [comment]
Yes, ChopDown can be disabled without breaking any functionality.

It's worth mentioning though that tree farms are the intended way to move forward in producing lots of lumber.  They're fairly affordable early on with Steve's Carts, as the cart recipes have been heavily tweaked.

Either way, I hope you enjoy the pack.
