### ISSUE TITLE
[1.10 / Quest] Unable to complete "Meet Pig" Quest

### ISSUE THREAD

**Issue by Colmund** [WesCook/Homestead#85]
On a new Server 1.10 we have a problem with the "meet pig" Quest in the farming section. It seems that the quest doesn't recognize the animania pigs. 
I known there is the same issue under the closed issue section and i already followed your instruction to update the Questfile. Unfortunately that didn't resolve the issue.

**Comment by WesCook** [comment]
Thanks for the report (and for searching first!).  I'm able to confirm this issue.

Not sure exactly how to fix it though, other than removing the quest...  Animania splits the mobs up into many subtypes, so I can't search for one of them specifically.  Previously the detection would inherit from the vanilla variant, but that appears to have been broken at some point.

In the mean time, you can mark the quest as completed manually by typing `/bq_admin complete 83` as an OP, or by putting the book into Edit Mode.

**Comment by Colmund** [comment]
Thanks for your help. I've used your workaround to complete the quest. 
By the way, my girlfriend and i are really enjoying your modpack- great work.

**Comment by WesCook** [comment]
I think in the next version I'll just change the quest to be a simple checkbox quest instead.  It's not quite as immersive and you lose the "Hey you found pigs!" notification, but it's better than a broken quest.  It's mostly intended as to be informational anyway so I'd rather not remove it completely.

Thanks for your report (and kind words!).  I'll leave this open for now as a reminder to adjust the quest next time I work on the pack.

**Comment by WesCook** [comment]
This has been addressed in Homestead v1.10.1.  To receive the quest changes, please remember to update your quest book:

>**Note:** Existing worlds will not automatically receive quest changes on pack updates.  On clients, you can run `/bq_admin default load` as an op to update existing worlds.  On servers, please copy the file `/config/betterquesting/DefaultQuests.json` over `/world/betterquesting/QuestDatabase.json`.
