### ISSUE TITLE
[QoL]Bronze > Iron nuggets

### ISSUE THREAD

**Issue by Raccoon2709** [WesCook/Homestead#87]
I have a problem with the System to gather Iron Nuggets to make a Iron Pick, to farm Iron. I dont get the idea.

Better use realistic stuff when you focus on it like Bronze which is a mixture between Tin and Copper. TiC should have it itself. (No idea if Tin is in there) Otherwise i would suggest [PFAA](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1293751-per-fabrica-ad-astra-geologica).

Do you need some Quests or something on the first view it's meh.

**Comment by WesCook** [comment]
Hi Raccoon,

Are you suggesting that copper and tin nuggets be added as drops for water strainers, rather than iron nuggets, so that they can be combined in the smeltery to make bronze?

I'm afraid I'm not totally clear on your question/suggestion.  I'd appreciate any clarification.  Thanks!

**Comment by Raccoon2709** [comment]
Sorry, my bad. 

I would suggest to disable the iron drops from the strainers and make the "Iron" Tier out of Bronze. 
€dit: After reading it, sorry for this bs. My Idea was to make it realistic and use the Tin and Copper Mixture to gather Bronze, because thats have a similar hardness (IRL) as Iron.

**Comment by WesCook** [comment]
Okay, so it would be mining copper and tin ores with the previous tier pickaxe (flint/cactus) and then combining them in a smeltery.

The biggest issue there is that tin doesn't actually exist in Homestead worlds right now.  Basically none of the tech mods needed it, so it seemed superfluous to add it.

While I'm not in love with iron nuggets being a semi-renewable resource, I think it's also a bit too early to send people into the caves as well.  If we were looking at just copper that might be okay as it's often found in mountains and near the surface, but this does change the flow of tech progression quite a bit.  And I'm pretty hesitant to make any major progression changes this long after the pack's initial release.

Thanks for the suggestion all the same.  If that addresses your point, I'll mark this one as closed.  Cheers!

**Comment by Raccoon2709** [comment]
Absolutly, i understand your position and thanks. (👍
