### ISSUE TITLE
Quest Book Blank

### ISSUE THREAD

**Issue by mcsunnishines** [WesCook/Homestead#88]
My quest book is suddenly blank, tried to reinstall the pack, but it didn't help.

**Comment by WesCook** [comment]
Could the quest data be corrupt in the world?  Try reloading the default quest data using one of these methods:

>On clients, you can run `/bq_admin default load` as an op to update existing worlds.
>On servers, copy the file `/config/betterquesting/DefaultQuests.json` over `/world/betterquesting/QuestDatabase.json`.

**Comment by mcsunnishines** [comment]
Thanks for the quick reply! I had done a quick search before asking and found those directions. 

I'm on a personal world on the ATlauncher, but I didn't check the cheat box when I made the world, so I can't run the first one. And I don't have a world folder? I downloaded the DefaultQuests.json from github and  replaced mine with it -- but that didn't work either.

**Comment by mcsunnishines** [comment]
I had installed journey map before -- but I'm almost positive that I had used the quest book after that because I did it right when I made the world. Anyways, I uninstalled journeymap after I realized the quest book was broken thinking that might have fixed it, but no. I tried the steps above after doing a reinstall of the instance, so they were done after removing journeymap. So as of now I have a fresh install of the modpack as it was released. I'm heading to try a new world now and see if that's what the screwup is. (something to do with installing journeymap into the modpack that got saved in my world)

**Comment by WesCook** [comment]
For future reference you can open a world to LAN as a way to temporarily enable cheats.  Though with modded worlds I always recommend leaving cheats enabled anyways, just in case things go wrong.

**Comment by mcsunnishines** [comment]
Yeah... I'm starting to realize that I should have left cheats on. I did open a new world and it still doesn't work.

**Comment by mcsunnishines** [comment]
New world, cheats on, ran /bq_admin default load and still nothing.

**Comment by WesCook** [comment]
Can you take a screenshot of the blank book?  Also, you said the book was "suddenly blank".  Does that mean it was working before?

Unfortunately though I'm not sure I'll be able to provide an explanation even with these answers.  You may need to try the [Better Questing bug tracker](https://github.com/Funwayguy/BetterQuesting) instead.  I've done a search and see they have a similar bug report: https://github.com/Funwayguy/BetterQuesting/issues/308

You might try updating their tracker with any relevant information as well.

**Comment by mcsunnishines** [comment]
![untitled](https://user-images.githubusercontent.com/38229918/38571767-0ff90bae-3cb7-11e8-958a-65612b8b496e.jpg)

It's just blank, and yes, it worked before. I'll go check their thread and see what I can do.

**Comment by WesCook** [comment]
Thanks for updating their issue.  I don't think there's much I can do from my end unfortunately, so I'm going to close this one for now.  If a solution is posted from BQ I'll be glad to incorporate it however.

I'm sorry that you weren't able to play the pack due to this issue.
