### ISSUE TITLE
empty quest log

### ISSUE THREAD

**Issue by egorananyev** [WesCook/Homestead#89]
Hi, first thanks so much for making such a wonderful mod pack! I'm having a blast with it.

However, several days in, after my computer crashed in a middle of a game, my quest log suddenly lost all of its content! I found that when I launched it next time. Since it was Windows that crashed, it didn't generate a crash report. Have you encountered this before? I'm starting another playthrough, since it's not a big deal, so I will let you know if this is recurring.
 
![2018-04-20_19 48 08](https://user-images.githubusercontent.com/6405803/39049494-43c6543a-44d4-11e8-9f70-8db67b672e1a.png)

**Comment by WesCook** [comment]
Hi,

This sounds like it's related to issue #88.  Unfortunately there isn't a fix available in the current version of the BetterQuesting mod so there isn't much I can do on my end.

In this case I think backups are the best way to avoid this issue.  There is an optional backup mod included in the pack, but it may or may not have been activated.  You may want to check to see if there's a copy of your world in there.

As this isn't a problem I can solve from my end though I need to mark this issue as closed.  But thank you for the report, I'm sorry that you ran into issues, and I hope you continue to enjoy the pack!

**Comment by egorananyev** [comment]
Thanks okay, I forgot that there's a backup. Thanks so much for your prompt response! And yes, the pack is still fantastic.
