### ISSUE TITLE
Screen goes black

### ISSUE THREAD

**Issue by DawoThePony** [WesCook/Homestead#9]
After few hours of gameplay everything just goes black. I can press escape and guess where is "Save and Quit to Titile" button and then main menu is normal. When I get back into the game it goes black again. First time loading backup fixed it, but now that it has happend second time it doesn't. I didn't see anything out of order in the normal logs and there is no crash log. (also I'm not native english speaker so sorry if I mistype or anything).

**Comment by WesCook** [comment]
I've not seen this issue yet, but it might be an OpenGL error.

There are two mods which apply shaders.  I'd suggest disabling them to start with.  They are [Blur](https://minecraft.curseforge.com/projects/blur) and [Enhanced Visuals](https://minecraft.curseforge.com/projects/enhancedvisuals).  You may also want to disable [Mo' Bends](https://minecraft.curseforge.com/projects/mo-bends), as that plays with rendering.

All three of these can be disabled through the pack reinstall screen.  Give that a try, and see if it has any effect.

If not, I'm not sure what else to suggest.  You might try updating your graphics card driver.  Though rendering issues in particular can be difficult to track down.

**Comment by DawoThePony** [comment]
It'e either Enchanced Visuals or Mo' Bends, because I first disabled Blur and nothing changed, and then I disabled all 3 and now it's working fine! Anyway, thank you very much, I was really enjoying the pack and it would be a shame if I couldn't play it.
