### ISSUE TITLE
Crashing upon opening it

### ISSUE THREAD

**Issue by sirblockwood101** [WesCook/Homestead#90]
Just downloaded a fresh install of homestead and everytime i open it from the ATLauncher it crashes! 
[crash-2018-04-28_16.20.06-client.txt](https://github.com/WesCook/Homestead/files/1958184/crash-2018-04-28_16.20.06-client.txt) Hope this works..this is the crash log of the last time i tried to open it!

**Comment by WesCook** [comment]
Mojang has a help page for this error.  Can you please try their suggestions?

https://help.mojang.com/customer/en/portal/articles/928791-problematic-frame-or-pixel-format-not-accelerated

**Comment by sirblockwood101** [comment]
wow thanks for the quick response! updating drivers now and will report back!

**Comment by sirblockwood101** [comment]
okay for those who are having the same problem make sure your drivers are up to date and if they are you might have bad drivers!

**Comment by WesCook** [comment]
Awesome, glad you got it resolved.  :)
