### ISSUE TITLE
Suggestion/Question

### ISSUE THREAD

**Issue by GottJammern** [WesCook/Homestead#91]
Hopefully I don't come off rude, but do you have plans to update to 1.12 before 1.13 is released, or are you waiting for it?
I'm sure you have enough on your plate already, I wasn't sure where to ask this though. Thank you!

**Comment by WesCook** [comment]
I've thought about 1.12.  It has strong mod support although a couple of the big mods I use like Realistic Terrain Generation and "WTF's Expedition" have not yet been updated.  Most likely it would be less of a port and more of a Homestead 2, if I were to update.

This pack took about 8 months to develop though - not to mention followup fixes - so it was a big undertaking.  I can't commit to another huge project like that right now.

If you're looking for something similar on a newer version, SevTech Ages is a pack that capture a lot of the early survival gameplay I was going for.  It's a little more structured than Homestead, but there's definite similarities.

Thanks for your question.

**Comment by Toksyuryel** [comment]
Realistic Terrain Generation isn't needed in 1.12 anymore because Quark offers a realistic world type.

**Comment by WesCook** [comment]
Quark's realistic setting is only a preset for the vanilla world generator.  It existed in 1.10 as well, but the results are very different from RTG.
