### ISSUE TITLE
Weird crash-like glitch?

### ISSUE THREAD

**Issue by TheSasaWorker** [WesCook/Homestead#96]
As context, I've played this modpack half an year ago, back when 1.11 just launched(or something like that don't remember exactly). I made a world, played for 'bout a month then stopped. Now I just got back into it on the same world without any issues besides lag worse than before(my pc isn't potato quality FYI), but that's beyond the point. Days went by without problems, though this evening the game started to bug. I fiddled with Fast Render & Graphics Quality(FR to On and Graphics to Fast) for better FPS. Then I got into some Creosote Oil(works in any liquid though) and the game literally showed my screen from 5 seconds ago once I hit head level. It did the same thing once I got out of head level.
Skip 5 minutes, then the game randomly blackscreens without a Not Responding icon. I recognize the bug from before(world was in Survival that whole time with my random GM1) so I do /gamemode 1 and the black screen goes. Weird thing was once I did /gamemode 0 the blackscreen appeared again and /gm 1 got it off.
I tried getting off the world and returning(+ fiddling around with graphics and render settings) and it fixed itself for 5 minutes. Then I asked for help on the AT Launcher Discord- to no avail, the Mod only recommended me that I check the Drivers and ask in your Discord or whatever. I also reinstalled the Instance of the Homestead modpack, no fix though.
Any help please? If need be I can screenshot my world, perhaps it's something inside causing this.
It's not the drivers probably though, since it just happened and no update came inbetween.
**Waiting for an answer ASAP so I can play this awesome modpack :)**

**Comment by WesCook** [comment]
My guess is when you entered the liquid, it applied an "underwater" shader effect which caused issues for your GPU driver.  Could you try the Reinstall button in ATL and deselect the "Enhanced Visuals" mod?

That would be my best guess anyway.  If that mod isn't the cause, then I'm not too sure.  You might try deselecting the other visual mods as well as Optifine to see if that makes any difference.

**Comment by TheSasaWorker** [comment]
Alright, I'll try this later. I've already tried reinstalling the modpack
with no success as I've originally said

**Comment by TheSasaWorker** [comment]
Noticed a new bug just now(been playing in Creative for a while) whenever my cursor goes on the JEI menu, it turns to weird night-day thing. The sun is still up- though the sky is dark like it's night. When my cursor goes off the JEI menu the bug is gone.
![image](https://user-images.githubusercontent.com/43584270/46091701-04013300-c1bc-11e8-9912-471ca4a50fe1.png)

**Comment by WesCook** [comment]
Optifine traditionally has issues with JEI like darkening backgrounds.

**Comment by TheSasaWorker** [comment]
I'll be damned, it worked. Removed all Visual mods and that fixed it. My guess would be a visual mod(forgot which) had a conflict with OpenGlider(it stated that when hovering over it).
Thanks a lot! I'll type more if anything occurs.
