### ISSUE TITLE
Crashing in Savannah Biome/Desert Biome

### ISSUE THREAD

**Issue by ReinhardtMB** [WesCook/Homestead#98]
Hello and good day, glad this github exists and that someone is actively working to improve and fix bugs for this amazing modpack! I was hoping I could get to the bottom of an issue that just about everyone who plays on my dedicated server has been facing -- Crashing at random times, seemingly only around our home on the savanna, at random places. I've included all of the crash reports from the time I started playing nearly two weeks ago, as you can see the crashes happen frequently, sometimes within 10 minutes of each other or less. I've recently disabled the better foliage mod to no avail, and just this morning disabled the movements mod (the one that adds custom animations). I will report back if this fixes the issue, but I wanted to include a detailed report because I'm not the only one having this issue. The crash itself leads to a blank screen (white, gray, tan, or light blue) and usually the cursor presents the loading symbol (the blue circle). Hope this helps, any information or fix would be greatly appreciated! Thanks and have a great day.

[crash-2018-10-09_15.34.35-client.txt](https://github.com/WesCook/Homestead/files/2499180/crash-2018-10-09_15.34.35-client.txt)
[crash-2018-10-09_15.41.47-client.txt](https://github.com/WesCook/Homestead/files/2499181/crash-2018-10-09_15.41.47-client.txt)
[crash-2018-10-09_15.56.07-client.txt](https://github.com/WesCook/Homestead/files/2499182/crash-2018-10-09_15.56.07-client.txt)
[crash-2018-10-09_16.26.08-client.txt](https://github.com/WesCook/Homestead/files/2499183/crash-2018-10-09_16.26.08-client.txt)
[crash-2018-10-09_17.40.56-client.txt](https://github.com/WesCook/Homestead/files/2499184/crash-2018-10-09_17.40.56-client.txt)
[crash-2018-10-09_19.40.50-client.txt](https://github.com/WesCook/Homestead/files/2499185/crash-2018-10-09_19.40.50-client.txt)
[crash-2018-10-09_20.43.21-client.txt](https://github.com/WesCook/Homestead/files/2499186/crash-2018-10-09_20.43.21-client.txt)
[crash-2018-10-09_21.55.45-client.txt](https://github.com/WesCook/Homestead/files/2499187/crash-2018-10-09_21.55.45-client.txt)
[crash-2018-10-09_22.01.10-client.txt](https://github.com/WesCook/Homestead/files/2499188/crash-2018-10-09_22.01.10-client.txt)
[crash-2018-10-09_22.18.19-client.txt](https://github.com/WesCook/Homestead/files/2499189/crash-2018-10-09_22.18.19-client.txt)
[crash-2018-10-10_11.53.08-client.txt](https://github.com/WesCook/Homestead/files/2499190/crash-2018-10-10_11.53.08-client.txt)
[crash-2018-10-10_12.13.34-client.txt](https://github.com/WesCook/Homestead/files/2499191/crash-2018-10-10_12.13.34-client.txt)
[crash-2018-10-10_12.29.16-client.txt](https://github.com/WesCook/Homestead/files/2499192/crash-2018-10-10_12.29.16-client.txt)
[crash-2018-10-12_12.28.28-client.txt](https://github.com/WesCook/Homestead/files/2499193/crash-2018-10-12_12.28.28-client.txt)
[crash-2018-10-12_13.23.26-client.txt](https://github.com/WesCook/Homestead/files/2499194/crash-2018-10-12_13.23.26-client.txt)
[crash-2018-10-12_13.54.18-client.txt](https://github.com/WesCook/Homestead/files/2499195/crash-2018-10-12_13.54.18-client.txt)
[crash-2018-10-13_13.38.46-client.txt](https://github.com/WesCook/Homestead/files/2499196/crash-2018-10-13_13.38.46-client.txt)
[crash-2018-10-13_14.17.03-client.txt](https://github.com/WesCook/Homestead/files/2499197/crash-2018-10-13_14.17.03-client.txt)
[crash-2018-10-13_14.25.23-client.txt](https://github.com/WesCook/Homestead/files/2499198/crash-2018-10-13_14.25.23-client.txt)
[crash-2018-10-13_21.47.59-client.txt](https://github.com/WesCook/Homestead/files/2499199/crash-2018-10-13_21.47.59-client.txt)
[crash-2018-10-13_22.20.30-client.txt](https://github.com/WesCook/Homestead/files/2499200/crash-2018-10-13_22.20.30-client.txt)
[crash-2018-10-14_09.07.42-client.txt](https://github.com/WesCook/Homestead/files/2499201/crash-2018-10-14_09.07.42-client.txt)
[crash-2018-10-14_18.37.20-client.txt](https://github.com/WesCook/Homestead/files/2499202/crash-2018-10-14_18.37.20-client.txt)
[crash-2018-10-14_18.58.29-client.txt](https://github.com/WesCook/Homestead/files/2499203/crash-2018-10-14_18.58.29-client.txt)
[crash-2018-10-14_22.03.27-client.txt](https://github.com/WesCook/Homestead/files/2499204/crash-2018-10-14_22.03.27-client.txt)
[crash-2018-10-14_23.52.28-client.txt](https://github.com/WesCook/Homestead/files/2499205/crash-2018-10-14_23.52.28-client.txt)
[crash-2018-10-15_00.04.23-client.txt](https://github.com/WesCook/Homestead/files/2499206/crash-2018-10-15_00.04.23-client.txt)
[crash-2018-10-15_00.11.12-client.txt](https://github.com/WesCook/Homestead/files/2499207/crash-2018-10-15_00.11.12-client.txt)
[crash-2018-10-15_12.23.05-client.txt](https://github.com/WesCook/Homestead/files/2499208/crash-2018-10-15_12.23.05-client.txt)
[crash-2018-10-15_12.34.13-client.txt](https://github.com/WesCook/Homestead/files/2499209/crash-2018-10-15_12.34.13-client.txt)
[crash-2018-10-15_12.38.51-client.txt](https://github.com/WesCook/Homestead/files/2499210/crash-2018-10-15_12.38.51-client.txt)
[crash-2018-10-15_16.20.37-client.txt](https://github.com/WesCook/Homestead/files/2499211/crash-2018-10-15_16.20.37-client.txt)
[crash-2018-10-15_16.46.27-client.txt](https://github.com/WesCook/Homestead/files/2499212/crash-2018-10-15_16.46.27-client.txt)
[crash-2018-10-15_16.55.32-client.txt](https://github.com/WesCook/Homestead/files/2499213/crash-2018-10-15_16.55.32-client.txt)
[crash-2018-10-15_21.24.56-client.txt](https://github.com/WesCook/Homestead/files/2499214/crash-2018-10-15_21.24.56-client.txt)
[crash-2018-10-16_14.01.22-client.txt](https://github.com/WesCook/Homestead/files/2499215/crash-2018-10-16_14.01.22-client.txt)
[crash-2018-10-16_14.12.52-client.txt](https://github.com/WesCook/Homestead/files/2499216/crash-2018-10-16_14.12.52-client.txt)
[crash-2018-10-16_14.24.08-client.txt](https://github.com/WesCook/Homestead/files/2499217/crash-2018-10-16_14.24.08-client.txt)
[crash-2018-10-16_14.46.53-client.txt](https://github.com/WesCook/Homestead/files/2499218/crash-2018-10-16_14.46.53-client.txt)
[crash-2018-10-16_19.11.14-client.txt](https://github.com/WesCook/Homestead/files/2499219/crash-2018-10-16_19.11.14-client.txt)
[crash-2018-10-16_20.29.45-client.txt](https://github.com/WesCook/Homestead/files/2499220/crash-2018-10-16_20.29.45-client.txt)
[crash-2018-10-16_21.26.46-client.txt](https://github.com/WesCook/Homestead/files/2499221/crash-2018-10-16_21.26.46-client.txt)
[crash-2018-10-20_10.16.16-client.txt](https://github.com/WesCook/Homestead/files/2499222/crash-2018-10-20_10.16.16-client.txt)
[crash-2018-10-20_23.19.01-client.txt](https://github.com/WesCook/Homestead/files/2499223/crash-2018-10-20_23.19.01-client.txt)
[crash-2018-10-20_23.26.32-client.txt](https://github.com/WesCook/Homestead/files/2499224/crash-2018-10-20_23.26.32-client.txt)
[crash-2018-10-20_23.33.57-client.txt](https://github.com/WesCook/Homestead/files/2499225/crash-2018-10-20_23.33.57-client.txt)
[crash-2018-10-21_00.41.32-client.txt](https://github.com/WesCook/Homestead/files/2499226/crash-2018-10-21_00.41.32-client.txt)
[crash-2018-10-21_09.35.53-client.txt](https://github.com/WesCook/Homestead/files/2499227/crash-2018-10-21_09.35.53-client.txt)

**Comment by ReinhardtMB** [comment]
UPDATE: Crashes continue despite disabling visual mods.

**Comment by WesCook** [comment]
Hey @ReinhardtMB.  Thanks for your detailed bug report.

Going off of the crash logs, it looks like this crash is caused by a bug in [Rustic](https://minecraft.curseforge.com/projects/rustic).  I checked their issue tracker and unfortunately it was never fixed on the 1.10 branch - which we are using.

https://github.com/the-realest-stu/Rustic/issues/3#issuecomment-297262472

My suggestion would be to remove the Rustic cabinet block(s) in your base, and I expect that should stop the crashing.  If you're unable to get close enough to do it manually, you can use a tool like [MCEdit](http://www.mcedit.net/) to remove the block instead.

Give it a try and let me know if that corrects your problem.  Thanks!

**Comment by ReinhardtMB** [comment]
Wow, thank you so much for the swift reply! Given that the mod is utilized in a dedicated server, would there be any issues with world generation/placement of those items if I outright removed the mod from the server/individual clients?

EDIT: In other words, will simply removing the mod remove all of the associated blocks in the world, or will we be forced to restart?

**Comment by ReinhardtMB** [comment]
Sorry for the double post, but another question:

Is the issue specifically related to cabinet blocks from Rustic, or other blocks from that particular mod as well? My group is discussing and considering how to proceed with our server, so our questions are sort of arising sporadically. Thank you again for all your help!

**Comment by WesCook** [comment]
From what I can tell of the crash log, simply removing the cabinets should solve the problem.  Failing that, you should also be able to remove the mod without major consequence.  Those items and blocks will disappear from the world.  Do note that the client and servers mods need to match.  Each client would also need to remove Rustic to connect to the server.

I'd start by just removing the cabinets and seeing if that solves the crashes.

**Comment by ReinhardtMB** [comment]
Ah, I see. You wouldn't happen to know if any cabinets spawn naturally in the world generation from Rustic mod would you? A buddy of mine placed about half a dozen cabinets... it would be quite hilarious if that was the only thing causing us to crash all this time! If nothing else spawns in the world, then I'll just remove those cabinets and report back in about 1-2 hours.

**Comment by WesCook** [comment]
As far as I know, there shouldn't be any naturally spawned.

**Comment by ReinhardtMB** [comment]
Happy to say roughly 2 hours of playtime and no crashes to report thus far after removing the half-dozen or so cabinets from Rustic mod! Will respond if any crashes arise, but so far so good!

**Comment by ReinhardtMB** [comment]
No crashes to report, will close this issue with a huge thank you for helping us to fix this major inconvenience with a small amount of work! Hopefully this can help someone else down the road as well!
